### ISSUE TITLE
Long MapPolyline disappears when zooming in

### ISSUE THREAD

**Issue by andyesys** [ClemensFischer/XAML-Map-Control#100]
Hi Clemens,

if I add the following static polyline to your MainWindow.xaml `<map:Map>` example:
```xml
            <map:MapPolyline Stroke="Black" StrokeThickness="3">
                <map:MapPolyline.Locations>
                    <map:LocationCollection>
                        <map:Location Latitude="49.30" Longitude="9.37"></map:Location>
                        <map:Location Latitude="52.47" Longitude="13.45"></map:Location>
                    </map:LocationCollection>
                </map:MapPolyline.Locations>
            </map:MapPolyline>
```

It is visible fine at first, but when I zoom in on it past level 16 or so, it disappears:

Level 16 (line visible):
![image](https://user-images.githubusercontent.com/30472657/213993798-ee632819-2c66-4fbd-b43a-53373cdcd3a0.png)

Level 17 (line disappears):
![image](https://user-images.githubusercontent.com/30472657/213993839-39bfceaf-4c0b-4994-bdaa-11adfe8f9774.png)

Can you please provide insight on the cause of the issue and suggestions for a fix?

**Comment by ClemensFischer** [comment]
Not sure what exactly happens, but the other endpoint of the line is very far outside the current viewport when the line disappears, something like 300000 pixels.
Maybe the MapPolyline implementation should calculate intermediate points to avoid this.
For now, you may use the LocationCollection.OrthodromeLocations or LocationCollection.LoxodromeLocations methods to create polylines with shorter distances between points.

**Comment by ClemensFischer** [comment]
It seems that the GetLayoutClip method returns a Geometry that somehow unexpectedly clips the MapPolyline when its bounds get very large.

When I override the method in MapPath like

    protected override Geometry GetLayoutClip(Size layoutSlotSize)
    {
        return null;
    }

the clipping is gone, although when zooming far in the rendered result slightly deviates from a normal Polyline with the same transformed points.

Another workaround could be two attached properties that are set on a normal Polyline:

    public class MapPolyline
    {
        public static readonly DependencyProperty ParentMapProperty = DependencyProperty.RegisterAttached(
            "ParentMap", typeof(MapBase), typeof(MapPolyline),
            new PropertyMetadata(null, (o, e) => Initialize((Polyline)o)));

        public static readonly DependencyProperty LocationsProperty = DependencyProperty.RegisterAttached(
            "Locations", typeof(IEnumerable<Location>), typeof(MapPolyline),
            new PropertyMetadata(null, (o, e) => Initialize((Polyline)o)));

        public static MapBase GetParentMap(Polyline polyline)
            => (MapBase)polyline.GetValue(ParentMapProperty);

        public static void SetParentMap(Polyline polyline, MapBase value)
            => polyline.SetValue(ParentMapProperty, value);

        public static IEnumerable<Location> GetLocations(Polyline polyline)
            => (IEnumerable<Location>)polyline.GetValue(LocationsProperty);

        public static void SetLocations(Polyline polyline, IEnumerable<Location> value)
            => polyline.SetValue(LocationsProperty, value);

        private static void Initialize(Polyline polyline)
        {
            var parentMap = GetParentMap(polyline);
            var locations = GetLocations(polyline);

            if (parentMap != null && locations != null)
            {
                parentMap.ViewportChanged += (s, e) =>
                {
                    polyline.Points = new PointCollection(locations
                        .Select(l => parentMap.LocationToView(l))
                        .Where(p => p.HasValue)
                        .Select(p => p.Value));
                };
            }
        }
    }

It would be used like this:

    <Polyline Stroke="White" StrokeThickness="2"
                local:MapPolyline.ParentMap="{Binding ElementName=map}">
        <local:MapPolyline.Locations>
            <map:LocationCollection>
                <map:Location Latitude="49.30" Longitude="9.37"/>
                <map:Location Latitude="52.47" Longitude="13.45"/>
            </map:LocationCollection>
        </local:MapPolyline.Locations>
    </Polyline>

**Comment by ClemensFischer** [comment]
Finally fixed this. The problem was that the PathGeometry by which a MapPolyline is drawn had a PathFigure with IsFilled set to false. Changed this to IsFilled = true.
Will soon make the next release.

**Comment by andyesys** [comment]
Thank you very much Clemens! This helps me a lot. ❤️
