### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'MapControl.TileImageLoader'

### ISSUE THREAD

**Issue by DBarzo** [ClemensFischer/XAML-Map-Control#101]
Hi Clemens,

I've used your great project for years on .net framework.
Now, I'm porting my project to netcore6 and I upgraded MapControl to latest version.

Unfortunatelly I run into a problem: the control give me the following exception:

`FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)`

![immagine](https://user-images.githubusercontent.com/6357293/214266920-9c420ad4-697a-4977-b20c-26d886d18239.png)

The runtime seems to not found System.Configuration.ConfigurationManager **but it is present into the folder!** (and it is the correct version).
I made some tests (also trying to use the source code direclty into my solution) but I cannot understand the reason.

Seems related to some assembly dependencies: your control is in a module used by another modules.

Do you have some hints on how to debug and solve this issue?

**Comment by ClemensFischer** [comment]
Sorry, but I have no idea what is happening there. I have never encountered that error in a .NET 6 or .NET 7 build.

Maybe take a look at the WPF sample application, which has build targets for .NET 7 and .NET Framework 4.8.

**Comment by ClemensFischer** [comment]
You may perhaps need to install a NuGet package: https://stackoverflow.com/q/47591910/1136211
