### ISSUE TITLE
Disable map repeat

### ISSUE THREAD

**Issue by SioGabx** [ClemensFischer/XAML-Map-Control#103]
Is it possible to somehow disable the fact that the map repeats to get similar behavior of what is done with the vertical axis (lock beyond the pole) ? 
Because it causes problems in my application : some objects teleport to one side or the other depending on where the view is.

For exemple :
![image](https://user-images.githubusercontent.com/41244237/216046998-242de8a5-ca61-479c-ae16-20b1ee32714b.png)
And if i move a little :
![image](https://user-images.githubusercontent.com/41244237/216047042-143ef4b2-1734-43cd-a2c7-b02f830b0f3e.png)
What i wanted is something like that : 
![Sans titreqsqqq-1](https://user-images.githubusercontent.com/41244237/216047693-7b69ccd6-7f20-495e-8573-ecdfc3b510ac.png)

**Comment by ClemensFischer** [comment]
No, this feature can not be disabled. You may limit the extent to which the map can be zoomed out by setting the MinZoomLevel property.
