### ISSUE TITLE
Search coordinate in polygon

### ISSUE THREAD

**Issue by Cieniu2009** [ClemensFischer/XAML-Map-Control#105]
Welcome,
I drew MapPolygon on the map, how can I check if the coordinates are within the mappolygon boundaries?
![image](https://user-images.githubusercontent.com/124438060/216805988-cc03c301-4222-407f-b54a-66408f0b6c1c.png)

For a rectangle it works fine, but I would need for a polygon

**Comment by ClemensFischer** [comment]
Find an appropriate algorithm on the internet.
