### ISSUE TITLE
Geodesic line?

### ISSUE THREAD

**Issue by o4oren** [ClemensFischer/XAML-Map-Control#109]
Well, this is a question, not an issue - 
Is there a way to draw a geodesic line on XAML-Map-Control? Or any shapes actually?

**Comment by ClemensFischer** [comment]
You can of course draw shapes. Please take a look at the sample application.
For a geodesic line, use the OrthodromeLocations methods of the LocationCollection class and use the result with a MapPolyline.

**Comment by o4oren** [comment]
Works like a charm.
What is the purpose of the altitude parameter in a Location object? Is there a way to tilt the map and see a path above the ground?

**Comment by ClemensFischer** [comment]
There is no "altitude parameter" in the Location class.
