### ISSUE TITLE
Complex DataTemplate

### ISSUE THREAD

**Issue by procfxgen** [ClemensFischer/XAML-Map-Control#11]
Hi,
 I create MapItems from a collection but I need to create a DataTemplate with an item with a Polygon and Image as on Image... how to do this ?

![test](https://user-images.githubusercontent.com/8511396/33442778-44100ca8-d5f6-11e7-8248-58452bd48817.png)

Ps. Circle grow but not Image ...

Thanks for your excellent Map Control !

**Comment by ClemensFischer** [comment]
No idea what exactly you're trying to do. Please take a look at the sample application. If there's anything specific you have trouble with, add more details to you question.

**Comment by procfxgen** [comment]
I need to do a dataTemplate like that

...
  <Grid.Resources>
    <DataTemplate x:Key="TemplatePointWithRayon" >

                <Grid>
                    <map:MapPolyline Locations="{Binding Locations}" Stroke="Red" StrokeThickness="3"/>

                    <Path map:MapPanel.Location="{Binding Location}" Stroke="Blue" StrokeThickness="3" Fill="#1F007F00">
                        <Path.Data>
                            <EllipseGeometry RadiusX="1852" RadiusY="1852" Transform="{Binding ScaleRotateTransform, ElementName=map}"/>
                        </Path.Data>
                    </Path>

                    <map:Pushpin map:MapPanel.Location="{Binding Location}" >

                        <Image Source="{Binding NormalBitmap}"></Image>
                        
                    </map:Pushpin>

                </Grid>
            </DataTemplate>
  </Grid.Resources>

 <map:Map x:Name="map" ZoomLevel="11" MaxZoomLevel="20" Center="43.6,1.44"  >

  <map:MapItemsControl ItemsSource="{Binding Visuals}"   IsSynchronizedWithCurrentItem="True"
                             ItemTemplate="{StaticResource TemplatePointWithRayon}"
                />

  </map:Map>

but that render this:


![image](https://user-images.githubusercontent.com/8511396/33473674-a32a4308-d677-11e7-95dd-3b46c0c9c030.png)


Thanks.
