### ISSUE TITLE
How to detect that the map is dragged?

### ISSUE THREAD

**Issue by o4oren** [ClemensFischer/XAML-Map-Control#110]
I can't find the event that would indicate user interaction moving the map, except if I used MouseButtonDown.
The context is that I go the map following an object by constantly updating the center property, but I want to enable the user to dragging off - and then losing the center on target follow, until selecting it again via a button.

**Comment by ClemensFischer** [comment]
There is no special event. Use the ViewportChanged event and perhaps set a flag to decide whether your code initiated a viewport change.
