### ISSUE TITLE
No access to MapContol.Caching.SQLiteCache or FileDbCache in my project

### ISSUE THREAD

**Issue by o4oren** [ClemensFischer/XAML-Map-Control#112]
While  TileImageLoader.Cache = new MapControl.Caching.ImageFileCache(TileImageLoader.DefaultCacheFolder) is working, trying the other cache options doesn't work:
e.g. TileImageLoader.Cache = new SQLiteCache(TileImageLoader.DefaultCacheFolder);

![Screenshot 2023-05-23 at 12 13 11](https://github.com/ClemensFischer/XAML-Map-Control/assets/23486326/62e6ece1-2f00-463b-902d-ee6d0cc88f87)

**Comment by ClemensFischer** [comment]
As always, you have to reference the assemblies that contain those classes.

**Comment by o4oren** [comment]
Not sure I follow. In my project, your package was added via Nuget.
I can't find these assemblies, and these don't work for me with your project directly either (at least not in WPF).

**Comment by ClemensFischer** [comment]
There is no NuGet package for the FileDbCache and SQLiteCache assemblies. You have to build the projects from source code.

**Comment by o4oren** [comment]
I see, thanks.
