### ISSUE TITLE
MapItemsControl - or any ItemsControl - doesn't work on my project

### ISSUE THREAD

**Issue by o4oren** [ClemensFischer/XAML-Map-Control#114]
I tried these two implementations:

           
                    <ItemsControl ItemsSource="{Binding Path=VatsimAircraft}" Visibility="Visible">
                        <ItemsControl.ItemsPanel>
                            <ItemsPanelTemplate>
                                <map:MapPanel AutoCollapse="False"></map:MapPanel>
                            </ItemsPanelTemplate>
                        </ItemsControl.ItemsPanel>
                        <ItemsControl.ItemTemplate>
                            <DataTemplate>
                                <map:MapItem
                                    Location="{Binding Location}"
                                    Margin="-16,-16,0,0"
                                >
                                    <Label Foreground="Black">here</Label>
                                </map:MapItem>
                            </DataTemplate>
                        </ItemsControl.ItemTemplate>
                    </ItemsControl>

And

                    <map:MapItemsControl ItemsSource="{Binding Path=VatsimAircraft}" Visibility="Visible">
                        <map:MapItemsControl.ItemTemplate>
                            <DataTemplate>
                                <map:MapItem
                                    Location="{Binding Location}"
                                    Margin="-16,-16,0,0"
                                >
                                    <Label Foreground="Black">here</Label>
                                </map:MapItem>
                            </DataTemplate>
                        </map:MapItemsControl.ItemTemplate>
                    </map:MapItemsControl>

Neither work, I cannot see the labels. 
If I just use StackPanel in the ItemsPanelTemplate, I will see the labels horizontally or vertically as set.
The whole thing is directly inside the MapContol.

What am I missing?

**Comment by o4oren** [comment]
I did take a look, it's binding to Polygons and PushPins - UI elements - in the model, which I cannot do in my case.
The VatsimAircraft is an ObservableCollection of objects with a Location property. Debugging it, I can see that they each have it's own Location. Location is the MapControl.Location type, created from LAT/LON doubles I get through the API.
Now, I would expect MapItems to be created in the location. The Label is just a test, they will be replaced by some vector graphic with text and tooltip, with dynamic rotation and scaling based n object parameters, but that's not the point. The thing is that I don't see the items on the map..

**Comment by ClemensFischer** [comment]
Without a full reproducible example there is no way to tell where you went wrong.

**Comment by o4oren** [comment]
Yes, I am sorry, but I can't get you the API access.

But with a regular ItemsControl, it prints the items and locations:
<img width="383" alt="image" src="https://github.com/ClemensFischer/XAML-Map-Control/assets/23486326/295e84aa-9d33-4c03-8936-cea066d3319e">

<img width="836" alt="image" src="https://github.com/ClemensFischer/XAML-Map-Control/assets/23486326/ca0e531f-ad3c-402d-ac19-3ba60c1401b8">

Then with the MapItemsControl, it's now ignores the location, and they're all stuffed in the top right corner and ignore the map dragging. Maybe that's why I missed them.
<img width="499" alt="image" src="https://github.com/ClemensFischer/XAML-Map-Control/assets/23486326/534c481a-53e8-48a2-b27b-84cfdc8eebe6">

<img width="835" alt="image" src="https://github.com/ClemensFischer/XAML-Map-Control/assets/23486326/b87fa797-2e9e-4010-82bb-59e8acb2a01f">

**Comment by ClemensFischer** [comment]
Not sure why you think there should be a MapItem in the ItemTemplate.  MapItem is the item container type of MapItemsControl and should have its Location bound in a Style, as shown in the sample application.

Here's a simple example:

    <map:MapItemsControl ItemsSource="{Binding Items}">
        <map:MapItemsControl.ItemContainerStyle>
            <Style TargetType="map:MapItem">
                <Setter Property="Location" Value="{Binding Location}"/>
            </Style>
        </map:MapItemsControl.ItemContainerStyle>
        <map:MapItemsControl.ItemTemplate>
            <DataTemplate>
                <StackPanel>
                    <TextBlock Text="{Binding Label}"/>
                </StackPanel>
            </DataTemplate>
        </map:MapItemsControl.ItemTemplate>
    </map:MapItemsControl>
