### ISSUE TITLE
Numerous updating items on map

### ISSUE THREAD

**Issue by o4oren** [ClemensFischer/XAML-Map-Control#115]
Hi,
I have a large amount of data items to display on the map (up to 2000) and they are represented in an ObservableCollection of objects.
On the map, they live in a MapItemsControl bound to that collection.
Rvery 15 seconds an async api call fetches a new list of items and updates the collection witha newly created one. On the map they are represented by different paths, with diferent colors and transforms (all derived from th3 data item).
Every time it is updated there is a 1-2 seconds freeze of the UI.
I tried different approaches, like looping and updating the collections ine by one from the external thread, changing vectors to images, putting them on overlays, etc.
I couldn't solve this completely. What would be the best approach to habdling updating a large list of items in the xaml map control?

**Comment by ClemensFischer** [comment]
How is anybody supposed to tell without seeing a single line of your code? And how is this related to a possible bug in the map control library? Be aware that this place is meant to track issues of the map control. It is not a place for general discussions like "how could I improve the performance of my WPF application?".
