### ISSUE TITLE
DataTemplate

### ISSUE THREAD

**Issue by procfxgen** [ClemensFischer/XAML-Map-Control#12]
Hi, 
I need to do a dataTemplate like that

    <Grid.Resources>
       <DataTemplate x:Key="TemplatePointWithRayon" >

                <Grid>
                    <map:MapPolyline Locations="{Binding Locations}" Stroke="Red" StrokeThickness="3"/>

                    <Path map:MapPanel.Location="{Binding Location}" Stroke="Blue" StrokeThickness="3" Fill="#1F007F00">
                        <Path.Data>
                            <EllipseGeometry RadiusX="1852" RadiusY="1852" Transform="{Binding ScaleRotateTransform, ElementName=map}"/>
                        </Path.Data>
                    </Path>

                    <map:Pushpin map:MapPanel.Location="{Binding Location}" >

                        <Image Source="{Binding NormalBitmap}"></Image>
                        
                    </map:Pushpin>

                </Grid>
            </DataTemplate>
     </Grid.Resources>

    <map:Map x:Name="map" ZoomLevel="11" MaxZoomLevel="20" Center="43.6,1.44"  >

      <map:MapItemsControl ItemsSource="{Binding Visuals}"   IsSynchronizedWithCurrentItem="True"
                             ItemTemplate="{StaticResource TemplatePointWithRayon}"
                />

     </map:Map>

but that render this:

![image](https://user-images.githubusercontent.com/8511396/33473674-a32a4308-d677-11e7-95dd-3b46c0c9c030.png)

Thanks.

**Comment by ClemensFischer** [comment]
The Location of a point item must be set by a Style Setter.

Try this:

    <map:MapItemsControl ItemsSource="{Binding Visuals}">
        <map:MapItemsControl.ItemContainerStyle>
            <Style TargetType="map:MapItem">
                <Setter Property="map:MapPanel.Location" Value="{Binding Location}"/>
            </Style>
        </map:MapItemsControl.ItemContainerStyle>
        <map:MapItemsControl.ItemTemplate>
            <DataTemplate>
                <Canvas>
                    <Path Stroke="Blue" StrokeThickness="3" Fill="#1F007F00">
                        <Path.Data>
                            <EllipseGeometry RadiusX="1852" RadiusY="1852" Transform="{Binding ScaleRotateTransform, ElementName=map}"/>
                        </Path.Data>
                    </Path>
                    <Image Source="{Binding NormalBitmap}" Width="100" Height="100" Canvas.Left="-50" Canvas.Top="-50"/>
                </Canvas>
            </DataTemplate>
        </map:MapItemsControl.ItemTemplate>
    </map:MapItemsControl>
