### ISSUE TITLE
MBTiles

### ISSUE THREAD

**Issue by superware** [ClemensFischer/XAML-Map-Control#120]
Hello @ClemensFischer,

Can you please create a NuGet package for `MapControl.MBTiles`?

Much appreciated!

**Comment by superware** [comment]
Thank you. Another thing, do you think it's possible to support GeoPackage? According to its [description](https://www.geopackage.org/guidance/getting-started.html), it seems `gpkg_tile_matrix_set.min_x/min_y/max_x/max_y` are "the actual spatial extents of the tile pyramid … applications can use this information to geolocate tiles correctly" and not necessarily the extents required.

**Comment by ClemensFischer** [comment]
Supporting the raster tiles option of the GeoPackage standard would of course be possible. I am however unable to find any database on the internet that actually contains tiles data. Without any usable test data it's not possible to implement it. Such test data should also cover the [Zoom Other Intervals](https://www.geopackage.org/spec120/#extension_zoom_other_intervals) extension.

**Comment by ClemensFischer** [comment]
Please note that there are now 3 separate packages, `MapControl.MBTiles.WPF`, `MapControl.MBTiles.WinUI` and `MapControl.MBTiles.Avalonia`
