### ISSUE TITLE
Right-to-left FlowDirection messes with map tiles layout

### ISSUE THREAD

**Issue by superware** [ClemensFischer/XAML-Map-Control#121]
WPF app with `FlowDirection="RightToLeft"` at the root, everything renders RTL except for the map control which is messed up. I guess something (tried `MapTileLayer` but still visibility issues) needs to be forced LTR and everything will be good. Any visual children such as `ContextMenu` etc must inherit `FlowDirection` from map's parent.

Thanks!

**Comment by ClemensFischer** [comment]
Sorry, the map control won't work with LTR. I'll add code that resets the FlowDirection property in the MapBase class.

For child elements where you need RTL, set it in global Styles, e.g. for ContextMenu.
