### ISSUE TITLE
Nuget includes unwanted WinUI components when targeting specific TargetFramework

### ISSUE THREAD

**Issue by OWiger** [ClemensFischer/XAML-Map-Control#122]
I need to have a specific TargetFramework set because of other nuget reference issues. 

But then XAML.MapControl.MapProjections drags MapControl.WinUI .dll into my WPF project when I need MapControl.WPF to be loaded instead. 

 ```
<PropertyGroup>
  <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
  <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <Platforms>x64</Platforms>
  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  <UseWindowsForms>true</UseWindowsForms>
  <UseWPF>true</UseWPF>
  <UseWinUI>false</UseWinUI>
  <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>	
</PropertyGroup>
```

**Comment by ClemensFischer** [comment]
Maybe it would be a good idea to drop multi-platform packages altogether and provide only platform-specific packages. I'll see if I can do that with the next release.

**Comment by OWiger** [comment]
> Maybe it would be a good idea to drop multi-platform packages altogether and provide only platform-specific packages. I'll see if I can do that with the next release.

Thanks! 
Amy idea of how I can resolve the issue now?

**Comment by ClemensFischer** [comment]
No

**Comment by ClemensFischer** [comment]
But I can make the release today...
