### ISSUE TITLE
MapBase's ViewScale accuracy

### ISSUE THREAD

**Issue by superware** [ClemensFischer/XAML-Map-Control#123]
Hello,

From the sample app:
```
<map:MapPath Location="53.5,8.2" Stroke="Blue" StrokeThickness="3" Fill="#1F007F00" IsHitTestVisible="False">
    <map:MapPath.Data>
		<EllipseGeometry RadiusX="1852" RadiusY="1852"/>
    </map:MapPath.Data>
</map:MapPath>
```

Why does the following appear smaller?

```
<Path map:MapPanel.Location="53.5,8.2" Stroke="Red" StrokeThickness="3" Fill="#1F007F00" IsHitTestVisible="False">
	<Path.Data>
		<EllipseGeometry RadiusX="1852" RadiusY="1852">
			<EllipseGeometry.Transform>
				<ScaleTransform ScaleX="{Binding ViewScale, ElementName=map}" ScaleY="{Binding ViewScale, ElementName=map}" />
			</EllipseGeometry.Transform>
		</EllipseGeometry>
	</Path.Data>
</Path>
```

**Comment by ClemensFischer** [comment]
This has nothing to do with accuracy.

The actual scaling factors of the transformation from world to view coordinates are the product of the ViewScale and the relative scale of the current map projections, as returned by the `MapProjection.GetRelativeScale(Location location)` method. For example in the web mercator projection, the relative scale values are greater than `1 / cos(latitude)`. The factors are not even always equal in x- and y-direction, as you can see in the equirectangular projection.
