### ISSUE TITLE
Can I use a single png file as my map?

### ISSUE THREAD

**Issue by UxxHans** [ClemensFischer/XAML-Map-Control#124]
Just need a simple custom ground map using a local png file.
 If anyone knows please tell me. Thanks a lot!

**Comment by ClemensFischer** [comment]
Add an `Image` to the Map and set the `MapPanel.BoundingBox` property.

    <map:Map ...>
        <Image Source="..." Stretch="Fill" map:MapPanel.BoundingBox="S,W,N,E"/>
    </map:Map>
