### ISSUE TITLE
MapPath Ellipse with Arrows

### ISSUE THREAD

**Issue by superware** [ClemensFischer/XAML-Map-Control#126]
Thanks to `MapPath` it's very easy to render a circle with meters radius, but I'm struggling with adding arrows to indicate direction:

![ellipse-direction](https://github.com/user-attachments/assets/4f5086d4-1217-4efb-9fd9-9ebe74e815ff)

```
<MapPath Location="{Binding Location}">
	<MapPath.Data>
		<EllipseGeometry RadiusX="{Binding Radius}" RadiusY="{Binding Radius}" />
	</MapPath.Data>
</MapPath>
```

If there's no way to do it with `MapPath`, then adding the arrows separately will also be fine (they should only offset from center, not scale). So it's simple to place them at `Location`, but how to offset by `Radius`? Thanks!

**Comment by ClemensFischer** [comment]
You would do that exactly as with a regular WPF Path. There is nothing specific about MapControl.

**Comment by superware** [comment]
But isn't offsetting by meters specific to MapControl? I'm just asking if there's a generic way of doing that in `XAML` without writing dedicated code that involves calculating the arrow location and then `LocationToView`.

The same way `MapPath` is using `Location` as the anchor point of geometries points in meters to make everything much easier, maybe `Margin` or `TranslateTransform` in meters could also be used to make offsetting much easier.

**Comment by ClemensFischer** [comment]
Think about how you would draw the same thing with a single Path with a GeometryGroup.

**Comment by superware** [comment]
Of course the arrows can be part of the geometry, but then they scale with the map since their points are in meters, which doesn't make much sense visually ("they should only offset from center, not scale").

It would be fantastic if there was a way to offset/translate elements by meters from `MapPath.Location`.

**Comment by superware** [comment]
@ClemensFischer I'm sorry but I still can't understand how you suggest to draw the arrow so it is located on the top of the ellipse and at the same time not scale with the map (while the ellipse does).

```
<MapPath Location="{Binding Location}">
	<MapPath.Data>
		<GeometryGroup>
			<EllipseGeometry RadiusX="{Binding Radius}" RadiusY="{Binding Radius}" />
			<PathGeometry Figures="..." />
		</GeometryGroup>
	</MapPath.Data>
</MapPath>
```

Points in `PathGeometry.Figures` will be in meters, so somehow will have to be modified at runtime as the map scales/radius change. Also, any shape `Figures` represents will itself scale with the map, so the arrow itself will change size instead of staying fixed (pixels).

Thank you!
