### ISSUE TITLE
Performance loss when popup is added

### ISSUE THREAD

**Issue by MatejNebrensky** [ClemensFischer/XAML-Map-Control#127]
Hello,
if I add e.g. empty ComboBox (or anything using popup) to the MainWindow (or any other window in my application which uses MapControl) and run the sample WPF application the map is moving/zooming fine, but if I click/open that combobox the performance goes down and does not recover when combobox is closed - shutdown and run again is needed. The problem is clearly visible with 10000 points or more on the map (in the Points collection in MapViewModel).
It is still perfect tool, thank You for it.

**Comment by ClemensFischer** [comment]
Hard to tell what exactly happens without any code...
