### ISSUE TITLE
Performance loss when any popup is opened

### ISSUE THREAD

**Issue by MatejNebrensky** [ClemensFischer/XAML-Map-Control#128]
If just "ComboBox" is added in the MainWindow.xaml of your WPF Sample Application like this:

            "...<Button Margin="2" Padding="8" ToolTip="Reset Heading" Click="ResetHeadingButtonClick"
                    FontSize="20" FontFamily="Segoe MDL2 Assets" Content="&#xEBE6;">
                <Button.Style>
                    <Style TargetType="Button">
                        <Style.Triggers>
                            <DataTrigger Binding="{Binding Heading, ElementName=map}" Value="0">
                                <Setter Property="Visibility" Value="Collapsed"/>
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </Button.Style>
            </Button>

            <ComboBox/>

        </StackPanel>
    </Grid>
</Window>"

and add some Points in MapViewModel constructor like this:

"...public class MapViewModel
{
    public List<PointItem> Points { get; } = new List<PointItem>();
    public List<PointItem> Pushpins { get; } = new List<PointItem>();
    public List<PolylineItem> Polylines { get; } = new List<PolylineItem>();

    public MapViewModel()
    {
        for (double i = 50; i < 60; i += 0.05)
            for (double j = 5; j < 10; j += 0.05)
            {
                Points.Add(new PointItem
                {
                    Name = $"{i}/{j}",
                    Location = new Location(i, j),
                });
            }

        Points.Add(new PointItem
        {
            Name = "Steinbake Leitdamm",
            Location = new Location(53.51217, 8.16603)
        });..."

opening the added Combobox causes big loss of performance while zooming or moving the map. Before opening the ComboBox everything is smooth.
It behaves the same if ComboBox or Menu is placed in other window in the same application than in that with the map.

**Comment by ClemensFischer** [comment]
20k items in a MapItemsControl is a totally unrealistic scenario. Performance is  already terrible without the ComboBox, at least on my system. I won't further investigate this.
