### ISSUE TITLE
Programatically created MapItemsControl changing style of pushpins

### ISSUE THREAD

**Issue by KAIN-Labs-Developer** [ClemensFischer/XAML-Map-Control#130]
Hello, the issue I am having is really that the horizontal and vertical alignments of the pushpins change when added to a MapItemsControl that is created dynamically at runtime. If I add the pushpins directly to the map (I.E. map.Children.Add(pushpin)), then they are perfect, with the location being in the bottom-center of the pin. But, when added to the MapItemsControl, the location is at the top-left corner of the pushpin.

It looks similar to this issue, but, since the MIC is being created at runtime, I cannot set it's ItemContainerStyle in the xaml. 
https://github.com/ClemensFischer/XAML-Map-Control/issues/85 

I am using the WPF version. Any advice would be greatly appreciated. 

P.S. I am transitioning from the Bing Maps WPF control and am using the MIC to replace the MapLayer class. Aside from this issue, the transition has been going a lot smoother than expected. Thank you for your good work!

**Comment by ClemensFischer** [comment]
You could set an ItemContainerStyle in code, i.e. load it from a Style Resource or create it dynamically.

    mic.ItemContainerStyle = (Style)Resources["PushpinItemStyle"];
