### ISSUE TITLE
UIElement size

### ISSUE THREAD

**Issue by procfxgen** [ClemensFischer/XAML-Map-Control#14]
![image](https://user-images.githubusercontent.com/8511396/33835964-616bafe2-de88-11e7-8450-811d7c07123a.png)

I need to implement mouse event on MapPanel but UIElement do not cover all ellipse geometry. X and Y start on middle of ellipse.... if I add Fill="Strech" to Path then ellipse middle is not longer to Location.

Thanks.

 <Path map:MapPanel.Location="53.5,8.2" Stroke="Blue" StrokeThickness="3" Fill="#1F007F00">
                <Path.Data>
                    <EllipseGeometry RadiusX="1852" RadiusY="1852" Transform="{Binding ScaleRotateTransform, ElementName=map}"/>
                </Path.Data>
            </Path>

**Comment by ClemensFischer** [comment]
?

**Comment by procfxgen** [comment]
Sorry but it's not a basic WPF things, there is a problem with map control's MapItem Location.
