### ISSUE TITLE
Option to disable FileDbCache cleanup on startup

### ISSUE THREAD

**Issue by superware** [ClemensFischer/XAML-Map-Control#15]
`public FileDbCache(string path, bool autoFlush = true, int autoCleanThreshold = -1, bool cleanNow = true)`

Will add an option to maintain all expired tiles on startup. This is a must feature in cases where the used device is usually offline, so it will still be possible to view all cached tiles.

Can you please consider this non breaking change? Thanks.

**Comment by ClemensFischer** [comment]
You may easily create your own version of FileDbCache. It isn't part of the NuGet package anyway.
