### ISSUE TITLE
MapPolyline disappearing when crossing center of viewport

### ISSUE THREAD

**Issue by Tiberiusva** [ClemensFischer/XAML-Map-Control#16]
It appears in WPF that since MapPolyline inherits from MapPath the MapPath.OnViewportChanged does not properly set the longitude offset because the Location object is always null. This can be fixed by using a location that is part of the location collection instead of the Location point which will always be null for a line.
to reproduce add a line in the SampleApps WpfApplication.MapViewModel that crosses the IDL
  Locations = LocationCollection.Parse("47.68,200 45,160")

Note that it will always stay on the right side of the viewport and not the left when zoomed out and will disappear when the center of the line crosses the viewport center line.

**Comment by ClemensFischer** [comment]
This behaviour is intended. You can optionally set the Location property to any sensible value of your choice.
