### ISSUE TITLE
MapProjection.ViewportTransform resolution issuein UWP MapControl sample

### ISSUE THREAD

**Issue by fobrs** [ClemensFischer/XAML-Map-Control#17]
When using the UWP sample app to zoom in to Fukushima (Japan), the MapGraticule rendering is jerky when panning the map at max zoom level.

The problem here is the resolution of the MapProjection.ViewportTransform matrix. Somehow it's values are converted to floats instead of doubles. 

I solved this problem in my project by having an extra copy of the render transform matrix: MapProjection.ViewportTransformMatrix. In the function MapProjection.SetViewportTransform() you need a LocationToPointD() function too, which returns a PointD (based on doubles). Likes this:

`        public virtual void SetViewportTransform(Location projectionCenter, Location mapCenter, Point viewportCenter, double zoomLevel, double heading)
        {
            ViewportScale = GetViewportScale(zoomLevel);
            PointD center = LocationToPointD(mapCenter);
            ViewportTransformMatrix = MatrixEx.TranslateScaleRotateTranslate(
                -center.X, -center.Y, ViewportScale, -ViewportScale, heading, viewportCenter.X, viewportCenter.Y);
            ViewportTransform.Matrix = ViewportTransformMatrix;
        }
`
Then I needed a double Matrix transform function: 

` public Point LocationToViewportPointD(Location location)
        {
            Point p = LocationToPoint(location);
            return new Point(ViewportTransformMatrix.M11 * p.X + ViewportTransformMatrix.M12 * p.Y + ViewportTransformMatrix.OffsetX,
                              ViewportTransformMatrix.M21 * p.X + ViewportTransformMatrix.M22 * p.Y + ViewportTransformMatrix.OffsetY);
        }
`
This function is used to position the labels in the MapGraticule. The graticule lines are transformed as needed by using this function without the use of geometry.Transform. Now the Graticule lines need to be rendered every time on OnViewportChanged().

To remove to jerkiness in the rendering of my own data I use own transform functions which make use of the MapProjection.ViewportTransformMatrix.

Hope I could have helped you in making this map control better.

**Comment by ClemensFischer** [comment]
The reason why the "jerkyness" disappears is that your "graticule lines are transformed as needed by using this function without the use of geometry.Transform" (similar to the last changes in the MapPolyline class).

It does however not matter if you keep another copy of the viewport transform matrix or not. The MapTransform class behaves identically regardless whether you use ViewportTransformMatrix or ViewportTransform.Matrix. Obviously both matrixes are identical.

**Comment by fobrs** [comment]
If you look with a Debugger to the OffsetX and OffsetY members of ViewportTransform.Matrix you can see that the values are truncated from double to float. That will impact all further calculations with this Matrix which results in the jerkiness.

**Comment by ClemensFischer** [comment]
Please the the edited comment above. Although the final point calculation in LocationToViewportPoint(D) results in slightly different X and Y values, drawing is still "jerky" unless you recalculate the viewport transform in OnViewportChanged.

**Comment by fobrs** [comment]
I'm using and target win10 build 16299. But the same jerkiness is present on build 15063. 
I see the jerkiness on a Dell workstation, Dell precision laptop, Surface Pro 4 and Lumia 950XL.
You don't?

**Comment by ClemensFischer** [comment]
Of course I see the jerkiness. All I'm saying is that it doesn't disappear due to keeping another matrix. You just get other rounding errors, but the jerkiness is still there. The important point is to recalculate the viewport transform in OnViewportChanged. I'm going to provide an updated MapGraticule soon.

**Comment by fobrs** [comment]
Have you looked with the debugger at the OffsetX and OffsetY members of the ViewportTransform.Matrix at max zoomlevel and centered in Japan? The values calculated in TranslateScaleRotateTranslate() are truncated to float after they arrive in ViewportTransform.Matrix.

**Comment by ClemensFischer** [comment]
I know, but as said, that doesn't matter. You get other rounding errors (I guess in Point) with your ViewportTransformMatrix. In the end, the drawing is still jerky.

**Comment by fobrs** [comment]
After careful examination I see a jerkiness in the MapTileLayer zoom animation too at max zoomlevel. It looks like the centerpoint is jumping a few pixels and so are tiles. Only the UWP sample app is affected. It looks like Microsoft made a big mistake using floats in stead of doubles in crucial places (Point, MatrixTransform) in the UWP app model.

**Comment by ClemensFischer** [comment]
That's true. The rounding errors resulting from float calculations are really annoying. I've tried many ways to get around them, but without any satisfying result yet.

One thing you can do right now, is to write a WebMercatorProjection with a longitude offset that is set to a fixed value like e.g. 90 or 180 degrees when you are far away from the central meridian.

In LocationToPoint replace `TrueScale * location.Longitude` by `TrueScale * (location.Longitude - offset)` and in PointToLocation replace `point.X / TrueScale` by `point.X / TrueScale + offset`.

**Comment by fobrs** [comment]
The zoom-animation is jerky nearby the central meridian too!

**Comment by fobrs** [comment]
I've solved the jerkiness of the center point during the zoom animation t max zoom level.
In MapBase.UpdateTransform() on the line stating with: center = projection.ViewportPointToLocation(... 
use a ViewportPointToLocationD() version defined as:
`public Location ViewportPointToLocationD(PointD point)
{
            Matrix m_inv = MatrixEx.Invert(ViewportTransformMatrix);
            return PointToLocationD(MatrixEx.TransformD(m_inv, point));
}
`

**Comment by fobrs** [comment]
Here are my additions to MatrixEx:
`public static Matrix Invert(Matrix m)
        {
            double determinant = (m.M11 * m.M22) - (m.M12 * m.M21);

            if (determinant == 0.0)
            {
                throw new System.InvalidOperationException("Matrix Not invertable");
            }

            double invdet = 1.0 / determinant;
            return new Matrix(m.M22 * invdet,
                        -m.M12 * invdet,
                        -m.M21 * invdet,
                        m.M11 * invdet,
                        (m.M21 * m.OffsetY - m.OffsetX * m.M22) * invdet,
                        (m.OffsetX * m.M12 - m.M11 * m.OffsetY) * invdet
                        );
        }

        public static PointD TransformD(Matrix m, PointD p)
        {
            return new PointD(m.M11 * p.X + m.M12 * p.Y + m.OffsetX,
                                         m.M21 * p.X + m.M22 * p.Y + m.OffsetY);
        }
    }`

**Comment by ClemensFischer** [comment]
While I appreciate your effort, these changes don't have the desired effect on my side. Zooming in at locations with large longitude is still jittering. I'm also pretty sure that I had already tried this and a lot more before without success.

As a note, I would also appreciate if you'd reference the original source of the copied parts of your code. Obviously [Reference Source](https://referencesource.microsoft.com/#WindowsBase/Base/System/Windows/Media/Matrix.cs,13b7d422c46ba7a0) here.

**Comment by fobrs** [comment]
If you would like a copy of your original Mapcontrol project with my changes to cure the jitter, I am happy to send them to you...

**Comment by fobrs** [comment]
I have a zip file ready. You can download it from:

http://bigroses.net/mapcontrol/XAML-Map-Control-smooth_zooming_and_panning.zip

thanks for sharing your control. It’s working really smooth now even on a device with touch and to a zoomlevel of 22

**Comment by ClemensFischer** [comment]
Thanks for insisting on this. I've added own Point and Matrix classes to the UWP variant to work around these annoying rounding errors.

**Comment by fobrs** [comment]
Nice!
> As a note, I would also appreciate if you'd reference the original source of the copied parts of your code. Obviously Reference Source here.

But eh, you forgot to reference your copied code too! Same source obviously ;-)

**Comment by ClemensFischer** [comment]
If you take a closer look, you'll notice that I didn't copy anything.
