### ISSUE TITLE
Polylines stutter on map move with higher zoom rate

### ISSUE THREAD

**Issue by woehrl** [ClemensFischer/XAML-Map-Control#19]
Hi Clemens,
when using a zoom level >20 there's a significant lack in precision where the polylines are drawn. On map move the Polylines seem to stutter then. Do you have any hint how to make the drawing more precise?
Best regards!
 Florian

**Comment by ClemensFischer** [comment]
This shouldn't be happening anymore with the latest version. Which version are you using?

**Comment by woehrl** [comment]
Thanks for your quick reply. I'm using the latest source, downloaded today. Is this problem connected with issue 17? Maybe the changes have not been applied to the WPF version of the control? I'm not using the UWP version. You can see the effect when changing the maxzoomlevel to 23 in the wpf demo:
127: <map:Map x:Name="map" ZoomLevel="11" MaxZoomLevel="23">

**Comment by ClemensFischer** [comment]
Please check the latest version 4.8.0. There is no Nuget package available yet.

**Comment by woehrl** [comment]
Hi Clemens, just wanted to thank you a lot. This looks perfect! Best regards, Florian
