### ISSUE TITLE
Is there a contribution policy?

### ISSUE THREAD

**Issue by heltonbiker** [ClemensFischer/XAML-Map-Control#2]
Is the project open to contributions? If so, what are the most needed areas? 

I have just stumbled into the project because I was planning to start a virtually identical one. I have also took a look at the BingMaps for WPF implementation and found it very tangled. Yours seems to be way simpler, more decoupled, more reusable, and more extensible, and of course _open_.

I'd be glad if I could contribute somehow, but i'm not sure what I could do that would be useful.

**Comment by ClemensFischer** [comment]
Sorry, the project isn't open for contributions. It will also not accept any pull requests.
