### ISSUE TITLE
Transforming a MapShape

### ISSUE THREAD

**Issue by fsaux** [ClemensFischer/XAML-Map-Control#22]
Hi Clemens,

Not an issue, just wanted your advice.
I'm deriving a class from MapShape which I'm intending to transform (Rotate and Scale centered on Location).
I've tried several things unsuccessfully like applying a RenderTransform(angle) or  RenderTransform(angle, Location.Longitude, Location.Latitude).
Looks like my shape is not rotating around the correct center.

Any clues?

Thanks,
Fernando.

**Comment by ClemensFischer** [comment]
Don't use a MapShape for point-like objects that are positioned at a specific Location. Instead use any UI element (e.g. Path) and set the MapPanel.Location attached property for positioning.
