### ISSUE TITLE
Polygons with holes

### ISSUE THREAD

**Issue by giswiz** [ClemensFischer/XAML-Map-Control#23]
I can't seem to figure out how polygons with holes work. If I declare a MapItem's style using MapMultiPolygon as ControlTemplate (using OSM boundries of the German Federal States), Berlin's area isn't punched out of Brandenburg, instead the color darkens:
```
  <Style x:Key="PolylinegonStyleLand" TargetType="map:MapItem">
    <Setter Property="Template">
      <Setter.Value>
        <ControlTemplate TargetType="map:MapItem">
          <map:MapMultiPolygon Polygons="{Binding Polies}" Stroke="Red" StrokeThickness="3" StrokeLineJoin="Round" Fill="#30FF0000" IsHitTestVisible="False" FillRule="EvenOdd"/>
        </ControlTemplate>
      </Setter.Value>
    </Setter>
  </Style>
```
(Fill is a little tranparent)
Brandenburg clearly has a hole: [https://wambachers-osm.website/boundaries/](https://wambachers-osm.website/boundaries/), search for 62504.
That's where I got the polygons from, I only use a Douglas-Peucker-reduction with different reductions for each zoom level. And an exclusion of off page features on the fly on Zoom and Pan changes. I've added a FillRule DependencyProperty to the MapMultiPolygon, passing it to the PathGeometry - no success.
I'm close to reimplementing MapMultiPolygon, MapPolygon and MapPolyline using DrawingVisual - using full featured Shape-objects to display hundreds of boundries (2,4,5,6,8)

**Comment by ClemensFischer** [comment]
Which version is this? The FillRule property was removed from MapShape.

**Comment by giswiz** [comment]
My fault: After lots of searching and writing GeoJson -> XAML file converters: My internal function "BastelRing", that was supposed to rearrange the polylines within a polygon, gracefully discarded any additional polygon (the "holes"). Rewriting it and renaming it to "BastelRinge" magically solved the problem: A feature is made of MultiPolygons: Each Polygon in this object is distinct and does not overlap any other (e.g. mainland and islands). If a Polygon is made up of multiple Linestrings, the first is (are?) the outer Polygon, the rest describe the holes. Now it's time to undo all my changes in your original code of the Map Control...
