### ISSUE TITLE
How to convert indiamap.osm.pbf file to file DB

### ISSUE THREAD

**Issue by rawat123** [ClemensFischer/XAML-Map-Control#31]
Hi,

I am trying to use the map control for offline maps,

I have downloaded a map in osm.pbf format file size is 450 mb.

as after enabling the cache mapcontrol creates a filedb file and stores the map data in filedb. and i can browse that data in offline mode.

so I want to provide my specific data in filedb format.

I searched a  lot but didn't found any utility to convert osm.pbf data in filedb.

how can I do that.

**Comment by ClemensFischer** [comment]
XAML Map Control does not natively support OSM raw/vector data, but rendered tile bitmaps only. Check the OSM wiki pages for how to render tiles from OSM data. I can not help you with that.
