### ISSUE TITLE
Change map color

### ISSUE THREAD

**Issue by rawat123** [ClemensFischer/XAML-Map-Control#32]
I want to change the color of map, I have created my tileserver and with leaflet.js I can add world.geo.json(https://github.com/johan/world.geo.json/tree/master/countries ) and can change the color, how can I achieve that same in xml map control,

issue I am having is when I print xml map control in black and white format the print quality is very bad, and when I print with leaflet.js with geo.json print quality is good in black & white format because I can manage the color.

**Comment by ClemensFischer** [comment]
If you have created a tile server, use an appropriate MapTileLayer with the tile server's URL, as shown in the example application. For the printing problem I have no idea how to help, because I don't know your code.
