### ISSUE TITLE
Can't update to 4.11.0

### ISSUE THREAD

**Issue by almostEric** [ClemensFischer/XAML-Map-Control#34]
Using NuGet, I can't update into a .Net 4.6.2 project - I think it is because the dependency information is missing

**Comment by ClemensFischer** [comment]
I have changed the target framework version of the WPF library to 4.7.2. Is that a serious problem for you?

**Comment by almostEric** [comment]
Yes.

I’d love to target 4.7.2 but it only works reliably on win10 and we have a lot of customers who haven’t migrated. Even 4.6.2 has caused issues but I figured 3 year old framework should be good enough 

Eric

Envoyé de mon iPhone

**Comment by ClemensFischer** [comment]
I have published a NuGet package 4.11.1, which also contains a version that targets .Net framework 4.6.2.
