### ISSUE TITLE
Bing map cache

### ISSUE THREAD

**Issue by shvarevdv** [ClemensFischer/XAML-Map-Control#35]
Hi, when i offline bingmap not showing images from cache.

**Comment by ClemensFischer** [comment]
BingMapsTileLayer always checks the Bing Maps Imagery Metadata Service for tile URLs. Their terms and conditions do not allow "pure" offline use. You can however directly access the cached image files by local `file://` URLs.

**Comment by shvarevdv** [comment]
Sory, but i don't understand, i must in Maplayers class in Tilesource write way to folder with tiles?

**Comment by ClemensFischer** [comment]
Use a MapTileLayer with a TileSource like

    TileSource = new TileSource
    {
        UriFormat = @"C:\ProgramData\MapControl\TileCache\Bing Maps Road\{z}\{x}\{y}.png"
    }

or similar, depending on where you cached files are stored.
