### ISSUE TITLE
MapScale Units

### ISSUE THREAD

**Issue by greateruser** [ClemensFischer/XAML-Map-Control#36]
Hi Clemens,

For folks across the pond in the US, would you mind implementing Imperial units (miles/feet) in the MapScale? It'd be pretty nifty with a property to switch between could be utilized. I've added MapControl to my project through NuGet.

Thanks!

**Comment by ClemensFischer** [comment]
And then also nautical miles and yards? I guess it would be quite easy for you to just make a copy of the class and modify it according to your needs.

**Comment by greateruser** [comment]
Thank you for the quick reply. I could certainly make a copy (I did try before posting here), and in the end decided it was best to request the feature be added so it's built in for anyone to use. I'm a novice at the scaling and inner workings of the mapping, so I'm sure you'd figure it out far quicker than I could. Any additional scaling unit options you add I'm sure will be found useful by someone.
