### ISSUE TITLE
[WPF] Open Street Map : 429 too many requests

### ISSUE THREAD

**Issue by TseuX** [ClemensFischer/XAML-Map-Control#38]
Hello,

Have you seen that ?

![image](https://user-images.githubusercontent.com/20822357/58897568-e5631c80-86f8-11e9-8cc7-8d0295dd7c92.png)

A work around is here : https://stackoverflow.com/a/15031536

Can you modify ImageLoader::LoadHttpStreamAsync please? 

This project is really useful.

Thank you.

**Comment by ClemensFischer** [comment]
There is nothing to fix in LoadHttpStreamAsync. Just identify your application by 

    ImageLoader.HttpClient.DefaultRequestHeaders.Add("User-Agent", "Your App");

**Comment by TseuX** [comment]
Thank you !
