### ISSUE TITLE
Point name binding problem?

### ISSUE THREAD

**Issue by mast3rm1nd** [ClemensFischer/XAML-Map-Control#4]
Trying following code which was in previous version, name of the point doesn't changes

```cs
var timer = new DispatcherTimer
{
	Interval = TimeSpan.FromSeconds(0.1)
};

timer.Tick += (s, e) =>
{
	var p = Points.Last();

	p.Location = new Location(p.Location.Latitude + 0.001, p.Location.Longitude + 0.002);

	p.Name = new Random().Next().ToString();

	if (p.Location.Latitude > 54)
	{
		p.Name = "Stopped";
		((DispatcherTimer)s).Stop();
	}
};

timer.Start();
```

**Comment by ClemensFischer** [comment]
It seems that changing the Text property in the OutlinedText class doesn't result in an OnRender call, although appropriate FrameworkPropertyMetadataOptions are set on its original declaration as TextBlock.TextProperty. I'll change the dependency property registrations with the next version.
