### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by cdm22** [ClemensFischer/XAML-Map-Control#40]
I get this error occasionally and it causes the APP to crash.

UWP  - Win 10 Pro 1803 (17134)
Visual Studio Pro 2019
XAML.MapControl 4.12.1

System.Runtime.InteropServices.COMException: 'Error HRESULT E_FAIL has been returned from a call to a COM component.'    bin\x64\Release\AppX\MapControl.UWP.dll

**StackTrace**
"   at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect)\r\n   at MapControl.MapPanel.ArrangeElementWithLocation(FrameworkElement element, MapBase parentMap, Location location)"

I'm having a difficult time pinpointing what might be causing this.
Do you have any idea what may be causing this?

Thanks!

**Comment by ClemensFischer** [comment]
Hard to tell without knowing your code. There is apparently some element in your application (which has the MapPanel.Location property set) that fails while it is arranged.
Layout processing has changed a bit in the newest version. Maybe try version 4.13.0. Either download from here or wait a couple of days for the next NuGet release.
