### ISSUE TITLE
Mouse event MapItemTouchDown does not fire in the MainWindow.xaml.cs on the WpfApplication

### ISSUE THREAD

**Issue by mlinnen** [ClemensFischer/XAML-Map-Control#41]
If you set a break point on the MapItemTouchDown method in the MainWindow.xaml.cs and launch the WpfApplication and use the left mouse click on any of the map items the break point never gets hit.

Not sure if something is consuming (handling) the event so that it never reaches the code behind or if it is something else.

**Comment by ClemensFischer** [comment]
Mouse input does of course not generate touch events. Use your finger on a touch screen.
