### ISSUE TITLE
Condiser same assembly name for WPF and WPF.Core

### ISSUE THREAD

**Issue by mahdi-ataollahi** [ClemensFischer/XAML-Map-Control#42]
In some cases that we want to use the control in multi-target projects like this:

```xml
<TargetFrameworks>netcoreapp3.0;net472</TargetFrameworks>
```

if we have a XAML file and want to add the Map control, then we should add this namespace for WPF:

```xml
xmlns:m="clr-namespace:MapControl;assembly=MapControl.WPF"
```

and this fot WPF.Core

```xml
xmlns:m="clr-namespace:MapControl;assembly=MapControl.WPF.Core"
```

so in multi-target project (that we have one XAML file for both) we can't use the control easily, and should write some code in cs file.

Please make the namespace of two projects the same, or merge them into one project!

thanks.

**Comment by ClemensFischer** [comment]
Good catch. Please check the latest version.
