### ISSUE TITLE
MapPolyline's locations collection after adding new items does not refresh UI

### ISSUE THREAD

**Issue by dgs28iun** [ClemensFischer/XAML-Map-Control#43]
Hi,

I am using MapControl in my project, and I noticed after adding locations for trace route, in real-time, to MapPolyline datatemplate from sample application in case of static map UI does not refresh. If I move map with mouse, polyline redraws on map.

Could you please check it?
Thanks
![mappolyline](https://user-images.githubusercontent.com/2790978/70646117-74388f00-1c70-11ea-8624-200db454eff9.png)

**Comment by ClemensFischer** [comment]
Use an `ObservableCollection<Location>` for the Locations property.

**Comment by dgs28iun** [comment]
It is working properly now, thank you very much
