### ISSUE TITLE
Setting HTTP User-Agent  and HTTP referer

### ISSUE THREAD

**Issue by janbuijs91** [ClemensFischer/XAML-Map-Control#44]
The standard openstreetmap tile server was updated to require a valid HTTP User-Agent and HTTP referer.
Without this, it doesn't work anymore.
Is there any way to set this when using this control?

See:
https://operations.osmfoundation.org/policies/tiles/
and
https://twitter.com/OSM_Tech/status/1214570195680927744

Thanks

**Comment by ClemensFischer** [comment]
As shown in the sample application:

ImageLoader.HttpClient.DefaultRequestHeaders.Add("User-Agent", "XAML Map Control Test Application");
