### ISSUE TITLE
[usage/general] Any suggestions on how to use GeoTIFFs?

### ISSUE THREAD

**Issue by bergziege** [ClemensFischer/XAML-Map-Control#45]
Hi, are there any experiences/suggestions out there on how to use GeoTIFF images (like from https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/vfr/) with the map control?

I have a small app for flight simulation (https://github.com/bergziege/XPlaneLauncher) where it would be nice to show some geotiff files (sector charts) on the map to give the user better route planing ability.

**Comment by ClemensFischer** [comment]
It would work out of the box like e.g.

    xmlns:img="clr-namespace:MapControl.Images;assembly=MapImages.WPF"
    ...
    <Image img:WorldFileImage.Path="Los_Angeles_106\Los Angeles SEC 106.tif"/>

provided that the world file (the .tfw) file would use WGS 84 as coordinate reference system.

You may perhaps convert those values, or try to provide an additional .prj file with the WKT of the current projection (although the projection may not be supported).

For details, please take a look at https://github.com/ClemensFischer/XAML-Map-Control/blob/master/MapImages/Shared/WorldFileImage.cs
