### ISSUE TITLE
how about support for ETRS89 / UTM zone 32N standard?

### ISSUE THREAD

**Issue by thicongtu2** [ClemensFischer/XAML-Map-Control#47]
i found your project missing this standard and only EPSG:4326 is hard code on MapProjection. in future how about add the ETRS89 / UTM zone 32N option?

**Comment by ClemensFischer** [comment]
Take a look at the MapProjections library that comes with the source code. It has a GeoApiProjection class where you can pass the WKT of any projections supported by ProjNET4GeoAPI. There is also a derived UtmProjection class where you can directly pass the UTM zone string, but it only supports WGS84.

**Comment by qxd4869** [comment]
Good morning. I want to have some follow-up question. When I tried the above solution. Using map tile server like this link does not work: https://www.wmts.nrw.de/webatlas/tiles/webatlas/EPSG_25832_15/{z}/{x}/{y}.png

The map shows up when I use WebMercatorProjection but it does not show the right conversion from long, lat to x, y

**Comment by ClemensFischer** [comment]
XAML MapControl does not support WMTS. To show a map in EPSG:25832 projection, you have to use a WmsImageLayer and set its ServiceUrl property to a WMS that supports the projection.

**Comment by qxd4869** [comment]
Thanks! Let me clarify: So it only supports tile-servers like Open Street Map and Google Map?

**Comment by ClemensFischer** [comment]
Sure

**Comment by ClemensFischer** [comment]
I have now added (a minimal) support for WMTS.

Assuming there is a Map element named `map` and a text file containing the WKT of the EPSG:25832 projection, you may use it like shown below. Note that you have to pass the WMTS Capabilities document instead of the tile URL template.

    map.MapProjection = new GeoApiProjection
    {
        WKT = File.ReadAllText("epsg25832.wkt")
    };

    map.MapLayer = new WmtsTileLayer
    {
        Capabilities = new Uri("https://www.wmts.nrw.de/webatlas/1.0.0/WMTSCapabilities.xml"),
        LayerIdentifier = "webatlas"
    };
