### ISSUE TITLE
GeoApiProjection convert point is not accuaccy when showing on google map

### ISSUE THREAD

**Issue by thicongtu2** [ClemensFischer/XAML-Map-Control#49]
i am using GeoApiProjection to showing a Weibadem WMS. it support EPSG:25832, so i using its WKT.
when i take a point in a WMS, it is converted it to coordinate in WGS84. and i using that coordinate to show in google map, it have some different. which can feel by eyes when zoom to 20m in google map

**Comment by ClemensFischer** [comment]
Please provide a minimal reproducible example.

**Comment by thicongtu2** [comment]
![image](https://user-images.githubusercontent.com/16049392/77498487-55a67e80-6e82-11ea-98c0-3130acd9c5a1.png)
![image](https://user-images.githubusercontent.com/16049392/77498636-b0d87100-6e82-11ea-892d-ffacb50a9de1.png)
I have mark this top of a bulding in Google map, the result is : 50°04'33.0"N 8°15'02.0"E
But when i using GeoApiMapProjection with EPSG:25832. and showing on MapControl, the result is:  N 50 04,545 ~ 50°04'32.0"N.

The link of wms is: [https://geoportal.wiesbaden.de/cgi-bin/mapserv.fcgi?map=d:/openwimap/umn/map/orthophoto/orthophotos.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities](url)

**Comment by ClemensFischer** [comment]
Sorry, I can not reproduce that. When I put a Pushpin at that location on a WmsImageLayer with that URL, I can change projections, and the Pushpin is always centered on the building.
I may provide some sample code later.

**Comment by thicongtu2** [comment]
thank you very much

**Comment by ClemensFischer** [comment]
Please check the new sample application ProjectionDemo. Right click for placing a Pushpin.

**Comment by thicongtu2** [comment]
i checked your demo app. the result is good, but i found:
```c#
return string.Format(CultureInfo.InvariantCulture,
                    "{0}  {1:00} {2:00} {3:00}\n{4} {5:000} {6:00} {7:00}",
                    latHemisphere, latitude / 3600, (latitude / 60) % 60, latitude % 60,
                    lonHemisphere, longitude / 3600, (longitude / 60) % 60, longitude % 60);
```
at this code, the lat/long may be is rounded. 
i checked on this point: the lat/long result is : `50.0757452,8.2505592` => after be round by the above formula: is `N  50 04 33 - E 008 15 02`
but actually if i paste to google: the result is: `50°04'32.7"N 8°15'02.0"E`.

Seem it only have a different at latitude.

Wait for your feedback

**Comment by ClemensFischer** [comment]
You realize that 32.7 rounded to integer is 33? You're free to modify the code so that is shows arc second as floating point value with a digit after the point?

**Comment by ClemensFischer** [comment]
No idea what Google Maps does there.

**Comment by thicongtu2** [comment]
I 'm sorry, I don't understand your comment.
I mean, we have some different in latitude between WMS with Google map. and I suppose it's bug.

**Comment by ClemensFischer** [comment]
You mean a bug in either ProjNET4GeoApi (which is used by the MapProjections library in XAML Map Control), or a bug in Google Maps?

Be aware that
- the offset you are observing is only ~10 meters,
- the aearial images show slanted buildings, where apparantly the position of the roof doesn't match the position of the ground floor
- and that we don't know the actual map projection Google uses to calculate the geo location it is showing in your image

**Comment by thicongtu2** [comment]
i mean the bug on ProjNET4GeoApi. but your explain make me clear.
thank you for your explain

**Comment by thicongtu2** [comment]
How can I synchronize map scale between Open street map and Wms?, actually  when i change map, i want the scale is the same for easy view.

**Comment by ClemensFischer** [comment]
The scale is determined by the current ZoomLevel, which doesn't change when you switch layers.

**Comment by thicongtu2** [comment]
![compare](https://user-images.githubusercontent.com/16049392/78527467-22130f00-7807-11ea-9639-562997f650c9.png)
as you see, with the ruler 50m in both maps, at WMS we can see all the building on side of the roundabout, and Open Street Map is not. and 50m ruler in WMS contain more pixel than OSM.
So, could i synchronize maps same size?

**Comment by ClemensFischer** [comment]
Note that the MapScale element shows the local scale at the center of the current viewport, while the ZoomLevel and hence the ViewScale property refer to the map scale at the line of true scale of the map projection, usually the equator. The local scale may differ for each projection and when you also change the projection together with the map layer, it is up to you to take this difference into account. MapProjection has a GetRelativeScale method, which you may use. You may also try the ZoomToBounds methods in MapBase.
