### ISSUE TITLE
MBTiles

### ISSUE THREAD

**Issue by Flozi95** [ClemensFischer/XAML-Map-Control#5]
Hi, 
I'm trying to realize a project using a provided MB tiles files as source for a WPF Map Application.
Could you maybe provide a small howto/example how i can load the data from the file?

Thank's!

**Comment by heltonbiker** [comment]
Hi @Flozi95 is the WPF Map application you're working on open source? If yes, would you post a link? I have interest in contributing.

**Comment by ClemensFischer** [comment]
You may create a derived TileSource class with an overridden LoadImage method that gets tiles images from an MBTiles file. Use your derived TileSource with a MapTileLayer as shown in the MapLayers class in the sample application.
