### ISSUE TITLE
How to calculate units per meter

### ISSUE THREAD

**Issue by qxd4869** [ClemensFischer/XAML-Map-Control#50]
Good morning, In MapProjection.cs, there is a block of codes:

/// <summary
/// Gets the map scale at the specified Location as viewport coordinate units per meter (px/m).
/// </summary>
public virtual Vector GetMapScale(Location location)
{
    return new Vector(ViewportScale, ViewportScale);
}

How can I get ground resolution of WMS from this block of codes?

**Comment by ClemensFischer** [comment]
Please define "ground resolution of WMS".

**Comment by gis-eastgate** [comment]
Hello Clemens, 
With a same question, i using your library, it is pretty good and easy to setup.
I have a application that have two layer: map control and drawer layer. with use google map, i can set the drawer layer ground resolution by the formula: 
```c#
distortedFactor = Math.Cos(latitude * Math.PI / 180);
groudResolution = distortedFactor * 40075016 / ((uint)TILE_SIZE << zoomLevel);
```
but when i try to use the WMS, the formula is not right, it make the point, the lane, circle i draw on the drawer-layer is diffrerent when switch to google map.

I try with your map, if i use the WMS (Weibadem). the zoom measure is changed. and scale is changed, but how can i change the above drawer-layer follow the map layer?

Many thanks.

**Comment by ClemensFischer** [comment]
That formula is for the web mercator projection. Do you use that projection with the WMS?

In order to put drawings on top of the map, use the coordinate transformation methods from the MapProjection class, not anything else.
