### ISSUE TITLE
cache for offline use

### ISSUE THREAD

**Issue by Derpeta** [ClemensFischer/XAML-Map-Control#52]
Hi,
I update XAML-mapcontrol from version 4.16.0 to 5.1.0.
After the update i can't use the cached tiles when offline. The map does not load the cached tiles anymore when offline. 
Don't know if this is a bug or that i need to change caching options? It works all fine when online.

there are pngs file present in the ~ProgramData\MapControl\TileCache\OpenStreetMap\{zoom}\{x}\{y}.png

```C#
ImageLoader.HttpClient.DefaultRequestHeaders.Add("User-Agent", "Meep");
TileImageLoader.Cache = new MapControl.Caching.ImageFileCache(TileImageLoader.DefaultCacheFolder);
```

WPF .NET Framework 4.8
XAML Mapcontrol V5.1.0

**Comment by ClemensFischer** [comment]
Just tested it, and it works fine for me. Maybe clear and re-create the cache, no idea.

**Comment by diededijkstraEA** [comment]
Does The TileImageLoader save/remember which tiles are cache or does it scan the cache folder if there are cached tiles present? I'm importing rendered tile (.png 256x256 8 bits) images from another source (renderer tool) in the tile cache folder. But MapControl does not show these tiles. When i connect to the internet. Tile are loaded en when disconnecting from internet, Only the tile will load that are downloaden from the internet connection. Other Tile are still in the cache folder. 
This was/still works on MapControl version 4.16.0.

**Comment by Derpeta** [comment]
Does The TileImageLoader save/remember which tiles are cache or does it scan the cache folder if there are cached tiles present? I'm importing rendered tile (.png 256x256 8 bits) images from another source (renderer tool) in the tile cache folder. But MapControl does not show these tiles. When i connect to the internet. Tile are loaded en when disconnecting from internet, Only the tile will load that are downloaden from the internet connection. Other Tile are still in the cache folder. 
This was/still works on MapControl version 4.16.0.

**Comment by ClemensFischer** [comment]
TileImageLoader does not do that.

You may debug into the GetExpiration method in ImageFileCache to check whether the expiration time stamp is not properly read from the image file. When writing a cached image file, ImageFileCache adds 16 bytes at the end with a tag string and an encoded expiration time. Maybe something goes wrong there.

**Comment by Derpeta** [comment]
Thanks, will have a look into this

**Comment by Derpeta** [comment]
That was indeed the problem. In TileImageLoader.WPF.cs GetCacheAsync(string) Line 78. object as ImageCacheItem returns null. For now i have changed it to:
```C#
var obj = Cache.Get(cacheKey);
var item = obj as ImageCacheItem;
if (item is null)
{
    var newItem = new ImageCacheItem();
    newItem.Buffer = (byte[])obj;
    newItem.Expiration = DateTime.UtcNow.AddDays(1);
    return Task.FromResult(newItem);
}
return Task.FromResult(item);
```

Works for me, Thanks again.

**Comment by ClemensFischer** [comment]
That doesn't make sense to me. It implies that Cache.Get returns a reference to an object that is not an ImageCacheItem. I fail to see how ImageFileCache would do that.

**Comment by Derpeta** [comment]
This is indeed stupid xD 

I changed the folder cache location. That was the problem......................................... sorry and thanks :P
