### ISSUE TITLE
Load tiles while moving the map

### ISSUE THREAD

**Issue by twarrendewit** [ClemensFischer/XAML-Map-Control#53]
In our application, the map moves and zooms constantly. However, it seems that new tiles only load when the map stops moving for a few moments.

Is that an illusion or is that intended behavior?

Is there a way for me to load tiles even while MapCenter and MapZoom are in constant flux?

**Comment by ClemensFischer** [comment]
Set the UpdateWhileViewportChanging property of the MapTileLayer to true.
