### ISSUE TITLE
Cache for WmsImageLayer?

### ISSUE THREAD

**Issue by mennowo** [ClemensFischer/XAML-Map-Control#54]
Hello,

is caching supposed to work for WmsImageLayer? I tried this following the example code in the sample WPF application, but see no image written to the folder provided.

I was trying this cause I wish to examine the images from the given WMS, cause they appear to have a white background. It would be nice to be able to specify a "tranparent color", though that may be outside of the scope of the library.

Thanks! Greets, Menno

**Comment by ClemensFischer** [comment]
No, caching makes no sense for WMS.

**Comment by ClemensFischer** [comment]
You may try if the WMS supports the TRANSPARENT parameter, i.e. "TRANSPARENT=TRUE".

**Comment by mennowo** [comment]
Thanks again for your replies. I was not aware a WMS creates a specific image at each request, sorry for that...!
The transperent parameter works great. I know you do not accept PR's, but maybe you can consider adding this as an option for the WmsImageLayer? This would allow configuring the option via the UI by databinding, etc.
Anyway, thanks again!
