### ISSUE TITLE
Scalability of MapItemsControl for large amount of points

### ISSUE THREAD

**Issue by bmulder-innoseis** [ClemensFischer/XAML-Map-Control#55]
I'm trying to display a lot of points (a simple dot together with a label) on a map using MapItemsControl.
When the amount of points gets to ~10k loading, panning and zooming of the map takes a very long time such that it is no longer workable.

Is there any way of speeding up this process or does something other than MapItemsControl exist to render a collection of points (which consist of radius, color, and x/y coordinates together with some text) in a more scalable way?

If not, can you perhaps make a suggestion on how to improve this and/or which parts of the current implementation could contribute to most of the performance overhead of rendering 10000 points?

Thank you for your time,
B. Mulder

**Comment by ClemensFischer** [comment]
Since elements on the map are positioned by standard WPF/UWP layout mechanisms, 10k objects are way too much.

An approach I can think of is to remove the whole layer (i.e. the MapItemsControl) when a map manipulation starts, and put it back in place when the sequence of manipulation events ends. Take a look at how the timer-controlled update mechanism in MapTileLayer works, where a DispatcherTimer is started or reset on each invokation of the Map's ViewportChanged event.

**Comment by bmulder-innoseis** [comment]
Thanks for your fast reply!

**Comment by bmulder-innoseis** [comment]
I tried the option you suggested and removed the MapItemsControl temporarily during manipulation with the ViewportChanged event using ```map.Children.Remove(itemsControl)``` (and Add them again when the timer expires).
Still, removing the itemsControl takes about two seconds while adding it again takes about 20, so this solution does not seem workable for me, unfortunately.
So I will look if I can either add my points as a static image into a single MapItem somehow or else see if I can make a modified version of Map-Control that uses some kind of clustering library.

**Comment by ClemensFischer** [comment]
What I have seen once at https://www.geocaching.com is that they seem to have kind of a dynamic map tile layer where they generate "overlay" tiles, containing geocache icons on a transparent background. This might well be possible with a derived TileSource that overrides the LoadImageAsync method.

**Comment by tipa** [comment]
I am coming from the now-deprecated UWP framework MapControl, which has great performance when displaying MapElements (tens of thousands of points and complex & long polylines). My goal is to visualize .kml or .gpx files, so they don't have to be user-interactable. Trying to show this data with a `MapItemsControl` causes the unusable performance described in this issue.

@bmulder-innoseis I know it's over four years since this issue has been created, but what did you you end up doing? I am considering either implementing a clustering algorithm that reduces the amount of items that are added to the `MapItemsControl`  (and perhaps remove items from the control that are outside the viewport) or implement some kind of transparent canvas layer that is put above the tile layer on which the polylines and points are drawn.

**Comment by bmulder-innoseis** [comment]
@tipa it's been a while since I worked on this but I kind of had the same issue where I did not really need the elements to be user interactable that badly.

What I ended up doing here was directly drawing them on a canvas (in fact, for ease of implementation I directly drew them on the tile layer, but if you want to do it properly, you can add another canvas layer).
The performance ended up to be great.

Currently I am working on a new software package for doing basically the same thing, but the GUI there is web-based and there I used Leaflet together with the leaflet markercluster library to achieve the same thing. The performance is not as good as with the canvas but at least the elements are interactable now which is a pro.

**Comment by tipa** [comment]
@bmulder-innoseis thanks for your response and sharing your epxerience with your workarounds - I will try the canvas-approach then as well

**Comment by tipa** [comment]
@bmulder-innoseis sorry for tagging you again, I'm just trying to avoid going into a wrong direction when implement this. Were you using a library like Win2D for the drawing or a system API that comes with the framework (UWP/WPF/WinUI3/...)? Seems like something like Win2D is appropriate for this kind of task, but it adds a dependency (and quite a few Megabytes) and you said you were directly drawing on the tile layer (while Win2D has it's own UI control), so you were probably using something else...

**Comment by bmulder-innoseis** [comment]
> @bmulder-innoseis sorry for tagging you again, I'm just trying to avoid going into a wrong direction when implement this. Were you using a library like Win2D for the drawing or a system API that comes with the framework (UWP/WPF/WinUI3/...)? Seems like something like Win2D is appropriate for this kind of task, but it adds a dependency (and quite a few Megabytes) and you said you were directly drawing on the tile layer (while Win2D has it's own UI control), so you were probably using something else...

No I didn't use any library, just a MapTileLayer with a custom TileSource subclass which overrides `public override async Task<ImageSource> LoadImageAsync(int x, int y, int zoomLevel)`
But it seems the whole API has changed since almost 5 years ago so you will need to find how to do it yourself

**Comment by tipa** [comment]
@bmulder-innoseis I think the TileSource class still has a virtual `LoadImageAsync` method, it's just not async any more. I could also fork the project and make adjustments to get it working. 

I'm just trying to understand what API you used to draw. The method you mention returns an `ImageSource`/`BitmapImage` - did you take that tile image, then draw on it using the `DrawingVisual` & `DrawingImage` classes and return the resulting ImageSource (similar to what is explained here: https://stackoverflow.com/a/21891278/3585218). Or another API?

Thanks so much for helping!

**Comment by bmulder-innoseis** [comment]
I used DrawingVisual.renderOpen() as a context to draw shapes on, then RenderTargetBitmap to render it and return that from the LoadImageAsync method

**Comment by ClemensFischer** [comment]
@tipa The last days I've been playing around a bit with Win2D for WinUI. The performance for CanvasGeometry with a large number of figures seems to be great. I have for example tried a geometry with a circle and two line segments at every intersection of integer latitude and longitude values, i.e. 170 * 360 * 3 = 183600 figures. The geometry is created once in projected map coordinates (i.e. meters) and subsequently only transformed by means of the Map's `ViewTransform.MapToViewMatrix`.

I am using a derived MapPanel

    public class MapCanvas : MapPanel
    {
        public event TypedEventHandler<MapCanvas, CanvasDrawEventArgs> Draw;

        public event TypedEventHandler<MapCanvas, CanvasCreateResourcesEventArgs> CreateResources;

        public MapCanvas()
        {
            Loaded += (s, e) =>
            {
                Canvas = new CanvasControl();
                Children.Add(Canvas);
                Canvas.Draw += CanvasDraw;
                Canvas.CreateResources += CanvasCreateResources;
            };

            Unloaded += (s, e) =>
            {
                Canvas.Draw -= CanvasDraw;
                Canvas.CreateResources -= CanvasCreateResources;
                Children.Remove(Canvas);
                Canvas.RemoveFromVisualTree();
                Canvas = null;
            };
        }

        public CanvasControl Canvas { get; private set; }

        public Matrix3x2? MapToViewTransform
        {
            get
            {
                if (ParentMap == null)
                {
                    return null;
                }

                var mapToViewMatrix = ParentMap.ViewTransform.MapToViewMatrix;

                return new Matrix3x2(
                    (float)mapToViewMatrix.M11, (float)mapToViewMatrix.M12,
                    (float)mapToViewMatrix.M21, (float)mapToViewMatrix.M22,
                    (float)mapToViewMatrix.OffsetX, (float)mapToViewMatrix.OffsetY);
            }
        }

        protected override void OnViewportChanged(ViewportChangedEventArgs e)
        {
            base.OnViewportChanged(e);

            Canvas?.Invalidate();
        }

        private void CanvasDraw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            Draw?.Invoke(this, args);
        }

        private void CanvasCreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args)
        {
            CreateResources?.Invoke(this, args);
        }
    }

in a sample application witrh these event handlers:

    private CanvasGeometry canvasGeometry;

    private void OnMapCanvasDraw(MapCanvas mapCanvas, CanvasDrawEventArgs args)
    {
        var t = mapCanvas.MapToViewTransform;

        if (t.HasValue)
        {
            var strokeWidth = Math.Max(1000F * (float)mapCanvas.ParentMap.ViewScale, 1F);
            var strokeStyle = new CanvasStrokeStyle
            {
                StartCap = CanvasCapStyle.Round,
                EndCap = CanvasCapStyle.Round
            };

            args.DrawingSession.DrawGeometry(canvasGeometry.Transform(t.Value), Colors.Magenta, strokeWidth, strokeStyle);
        }
    }

    private void OnMapCanvasCreateResources(MapCanvas mapCanvas, CanvasCreateResourcesEventArgs args)
    {
        var projection = mapCanvas.ParentMap.MapProjection;

        using var pathBuilder = new CanvasPathBuilder(mapCanvas.Canvas.Device);

        for (double lon = -180; lon < 180; lon += 1)
        {
            for (double lat = -85; lat <= 85; lat += 1)
            {
                var p = projection.LocationToMap(new Location(lat, lon));
                var x = (float)p.Value.X;
                var y = (float)p.Value.Y;
                var s = 10000F;

                pathBuilder.BeginFigure(x + s, y);
                pathBuilder.AddArc(new Vector2(x, y), s, s, 0F, 2F * MathF.PI);
                pathBuilder.EndFigure(CanvasFigureLoop.Open);

                pathBuilder.BeginFigure(x - s, y - s);
                pathBuilder.AddLine(x + s, y + s);
                pathBuilder.EndFigure(CanvasFigureLoop.Open);

                pathBuilder.BeginFigure(x - s, y + s);
                pathBuilder.AddLine(x + s, y - s);
                pathBuilder.EndFigure(CanvasFigureLoop.Open);
            }
        }

        canvasGeometry = CanvasGeometry.CreatePath(pathBuilder);
    }

**Comment by tipa** [comment]
Thanks so much to the two of you for helping and even providing code snippets!!

@bmulder-innoseis I tried to replicate what you did. It looks like while those APIs still exist on WinUI, they cannot be used in the UI/visual layer. `RenderTargetBitmap` has another constructor now, too...

@ClemensFischer that worked perfectly and performance is great! Only when trying to render a lot of individual points (POIs) as filled circles + outline (as shown in the small screenshot), I wasn't able to include them in the single `CanvasGeometry`, but had to create a single one for each. Still had decent render performance (~20ms) with thousands elements rendered.

![image](https://github.com/user-attachments/assets/32fc16d6-3512-44d8-bc5c-32487576b70c)

I guess there's no way around that additional Win2D dependency for now. When I find more time, I will try if there's a way to get similar results without an additional library (e.g. using the `Microsoft.UI.Composition` APIs). If I find something useful, I'll post it here.
