### ISSUE TITLE
Filled Polylines

### ISSUE THREAD

**Issue by paulrozhkin** [ClemensFischer/XAML-Map-Control#56]
Hi,

How to fill polyline?
I am using the following code:
```
<mapControl:MapPolyline Stroke="Black" Fill="Black" StrokeThickness="3" Locations="55.451002,78.270932  55.451223,78.271160 55.450946,78.271934 55.451002,78.270932"/>
```
But as a result Polyline is not filled:
![image](https://user-images.githubusercontent.com/38138387/83953887-ecad9080-a84c-11ea-8a1d-58ac2cb9c9fa.png)
Or can this only be implemented with Polygon? (before we used a framework where the polyline had the ability to fill)

**Comment by ClemensFischer** [comment]
You can only fill a MapPolygon.

**Comment by paulrozhkin** [comment]
Thanks for the answer. I did it before opening issue, it’s just that some bugs will appear in the project after that, which now have to be fixed. The attached code was not a project code.
