### ISSUE TITLE
Keyboard events on WPF Map not firing

### ISSUE THREAD

**Issue by bmulder-innoseis** [ClemensFischer/XAML-Map-Control#57]
When I add a KeyDown or KeyUp handler to the map, the handler is not called when I push a key when the map is focused.

I can reproduce this in the WpfApplication inside SampleApps by adding ```KeyDown="MapKeyDown"``` to the map element in MainWindow.xaml and installing an Appropriate handler in MainWindow.xaml.cs:

```private void MapKeyDown(object sender, KeyboardEventArgs e) { //add random code here }```

When I set a breakpoint on this line or do any other thing inside the function, it will never be reached.

I discovered this when upgrading the MapControl NuGet package from 4.2.0 to 5.2.1, but I have not tried any versions in between yet.

**Comment by ClemensFischer** [comment]
You have to set the Focusable property to true. The default is false.

**Comment by bmulder-innoseis** [comment]
I did that, it did not solve it.

**Comment by ClemensFischer** [comment]
Well, it works for me. Maybe you have a layer on top that somehow swallows the events.

**Comment by bmulder-innoseis** [comment]
I tried adding the handler and Focusable="True" to the demo on current master, and it does not work for me.
Same for my own application, where the problem disappears when I downgrade to 4.2.0 (and make no other changes)
Anything related to events changed between these versions? I cannot explain the differences.

**Comment by ClemensFischer** [comment]
I've added `map.Focusable = true; map.Focus();` after InitializeComponent, if that helps.

**Comment by bmulder-innoseis** [comment]
That works, but when I then click on something outside of the map and on the map again it does not work again. In other words, somehow the map is not focused when I click on it.

**Comment by ClemensFischer** [comment]
You may call Focus in some mouse event handler, according to your needs.
