### ISSUE TITLE
Duplicate SupportedCrs in WmtsTileLayer

### ISSUE THREAD

**Issue by mennowo** [ClemensFischer/XAML-Map-Control#58]
Hello,

while using [this WMTS](https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wmts/1.0.0/WMTSCapabilities.xml) I run into an issue with duplicate items in a dictionary. Specifically, this given WMTS has multiple TileMatrixSets with ""<ows:SupportedCRS>EPSG:3857</ows:SupportedCRS>". This leads to an exception in WmtsTileLayer.cs line 198.

Is this a fault in the WMTS, or something that might be resolved in the library? By changing the code like this:

```
capabilities.TileMatrixSets.ForEach(s =>
{
  if (!TileMatrixSets.ContainsKey(s.SupportedCrs)) TileMatrixSets.Add(s.SupportedCrs, s);
});
```

the WMTS functions fine.

Thanks, greets, Menno

**Comment by ClemensFischer** [comment]
Thanks for spotting that. I have committed a new version of WmtsTileLayer.cs.

I will have to check some other issues before releasing the next NuGet package.
