### ISSUE TITLE
Map move events do not work with MapItemsControl

### ISSUE THREAD

**Issue by paulrozhkin** [ClemensFischer/XAML-Map-Control#59]
When you add a container of elements to a map, such as a MapItemsControl, moving around the map does not work when you click on a child of MapItemsControl.
**Code example:**
```
<m:Map>
    <m:MapItemsControl>
        <m:MapPolygon Fill="Blue" Stroke="Green" StrokeThickness="5"
                      Locations="47.6424,-122.3219 47.8424,-122.1747 47.5814,-122.1747"
                      Opacity="0.7">
            <m:MapPolygon.Style>
                <Style TargetType="m:MapPolygon">
                    <EventSetter Event="PreviewMouseRightButtonDown" Handler="PolygonMouseRightButtonDown" />
                    <Style.Triggers>
                        <Trigger Property="IsMouseOver" Value="True">
                            <Setter Property="Cursor" Value="Hand" />
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </m:MapPolygon.Style>
        </m:MapPolygon>
    </m:MapItemsControl>
</m:Map>
```
**Demonstration:**
![gif1](https://user-images.githubusercontent.com/38138387/85141576-a5ad9b00-b24f-11ea-91e5-98ce918c0c27.gif)

If we remove the container, then the movement will be processed correctly. This is just an example, since we are losing Binding to ItemsSource.
**Code example:**
```
<m:Map>
        <m:MapPolygon Fill="Blue" Stroke="Green" StrokeThickness="5"
                      Locations="47.6424,-122.3219 47.8424,-122.1747 47.5814,-122.1747"
                      Opacity="0.7">
            <m:MapPolygon.Style>
                <Style TargetType="m:MapPolygon">
                    <EventSetter Event="PreviewMouseRightButtonDown" Handler="PolygonMouseRightButtonDown" />
                    <Style.Triggers>
                        <Trigger Property="IsMouseOver" Value="True">
                            <Setter Property="Cursor" Value="Hand" />
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </m:MapPolygon.Style>
        </m:MapPolygon>
</m:Map>
```
**Demonstration:**
![gif2](https://user-images.githubusercontent.com/38138387/85142295-cb876f80-b250-11ea-95a8-25fde23c7cc5.gif)

If we look, for example, at the Bing Maps Control, then the event of movement will be correctly processed by the children of MapItemsControl.
**Code example for bing maps:**
```
<m:Map
    CredentialsProvider="BING_MAPS_KEY">
    <m:MapItemsControl>
        <m:MapPolygon Fill="Blue" Stroke="Green" StrokeThickness="5"
                      Locations="47.6424,-122.3219 47.8424,-122.1747 47.5814,-122.1747"
                      Opacity="0.7">
            <m:MapPolygon.Style>
                <Style TargetType="m:MapPolygon">
                    <EventSetter Event="PreviewMouseRightButtonDown" Handler="PolygonMouseRightButtonDown" />
                    <Style.Triggers>
                        <Trigger Property="IsMouseOver" Value="True">
                            <Setter Property="Cursor" Value="Hand" />
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </m:MapPolygon.Style>
        </m:MapPolygon>
    </m:MapItemsControl>
</m:Map>
```
**Demonstration:**
![gif3](https://user-images.githubusercontent.com/38138387/85143674-b4e21800-b252-11ea-8a3e-35ba3b7ee7c5.gif)

Is it possible to somehow get the behavior as in the last example?

**Comment by ClemensFischer** [comment]
This is not how it supposed to be used. Take a look ath the sampe application to see how polylines are added to the map.

**Comment by ClemensFischer** [comment]
And please refrain from posting animated GIFs. That's the most annyoing thing in the world.

**Comment by ClemensFischer** [comment]
Please do not post animated GIFs. Describe the desired behaviour. Tell me what you expect and what exactly doesn't work.

**Comment by paulrozhkin** [comment]
When you add children to the map through MapItemsControl, the movement of the map will become unavailable when you click on children.
In my case, I have many semi-transparent polygons on the map and when I add them, they occupy most of the map space and I can’t move around the map in any way when I click on them. And no, I can’t use IsHitTestVisible = "false" on MapItemsControl.

Example as in SampleApp:
```
<Window.Resources>
         <DataTemplate x:Key="PolygonItemTemplate">
            <map:MapPolygon Locations="{Binding Locations}" Stroke="Red" Fill="Blue" Opacity="0.5" StrokeThickness="3"/>
        </DataTemplate>
</Window.Resources>

<Grid>
         <map:MapItemsControl ItemsSource="{Binding Polylines}"
                                 ItemTemplate="{StaticResource PolygonItemTemplate}"/>
</Grid>
```

**Comment by paulrozhkin** [comment]
As far as I understand MapItemsControl is inherited from ListBox, but not from ItemsControl, and events used on the map to move (OnMouseMove, OnMouseLeftButtonUp and OnMouseLeftButtonDown) are not forwarded to Map from child MapItemsControl elements. There is no way to move around the map with additional layers?

**Comment by ClemensFischer** [comment]
And no, I can’t use IsHitTestVisible="false" on MapItemsControl.
Then set IsHitTestVisible on the MapPolygon or the ContentPresenter?

**Comment by paulrozhkin** [comment]
> > And no, I can’t use IsHitTestVisible="false" on MapItemsControl.
> 
> Why not? Please don't make me ask all this.

If we have any events on a child of MapItemsControl, then we will not be able to handle them.  I specifically wrote an example with such a case, at the very beginning.

Code example:
```
<Window.Resources>
         <DataTemplate x:Key="PolygonItemTemplate">
            <map:MapPolygon IsHitTestVisible="False" MouseDown="UIElement_OnMouseDown" Locations="{Binding Locations}" Stroke="Red" Fill="Blue" Opacity="0.5" StrokeThickness="3"/>
        </DataTemplate>
</Window.Resources>
```
For this example, if we set IsHitTestVisible="False", then we will not be able to handle MouseDown.

**Comment by ClemensFischer** [comment]
Ok, it's a simple change. Set

    e.Handled = false;

in line 26 in MapItemsControl.WPF.cs. Or derive from MapItemsControl and override OnMouseLeftButtonDown.

I'll see if I can make this change in the library.

**Comment by paulrozhkin** [comment]
Ok, thank you. It works.

**Comment by ClemensFischer** [comment]
Be aware that now multiple overlapping polgons may be selected with a single click, which may conflict with the MapItemsControl's SelectionMode.
