### ISSUE TITLE
XAML Map Control disables Fluent Design Blur

### ISSUE THREAD

**Issue by MartinZikmund** [ClemensFischer/XAML-Map-Control#6]
# Problem
I have followed the tutorial in this StackOverflow answer to enable Acrylic Accent background for my UWP app:
https://stackoverflow.com/questions/43699256/how-to-use-acrylic-accent-in-windows-10-creators-update

Unfortunately, when I placed the XAML Map Control on the page, the blur on the background disappeared and was replaced by solid color.

## Expected behavior
Blur should stay active even when XAML Map Control is on the page. I have verified the problem does not occur when the built-in Map control is on the page.

**Comment by ClemensFischer** [comment]
Will look into the issue on occasion.
