### ISSUE TITLE
How to download cache

### ISSUE THREAD

**Issue by NguyenDinhTrong99** [ClemensFischer/XAML-Map-Control#60]
Hi bro,

My problem is load map offline, your library have performane amazing, so i want load all cache, meaning I want to get the entire cache without having to run the app in online mode and I still have the cache.. I try search in google but no find result.  I hope you help me!

Thanks u so much, u create a library excellent!

**Comment by ClemensFischer** [comment]
Be aware that content providers may explicity forbid this. Besides that, the library does not provide any support for such a feature. You have to implement it yourself.

**Comment by NguyenDinhTrong99** [comment]
Thanks for bro
