### ISSUE TITLE
Missing Tile Replacement

### ISSUE THREAD

**Issue by twarrendewit** [ClemensFischer/XAML-Map-Control#62]
I'm using XAML Map Control in an offline environment with an ImageFileCache of map tiles. When a tile is missing, I see two results:

1. If zooming in, it will stretch larger tiles it does have.
2. If panning when already zoomed it, it will be blank and show background color.

Is there a way for the map to always do Result 1, even if I start it zoomed in? It's preferable to have a stretched tile than to have nothing in my application.

**Comment by ClemensFischer** [comment]
If lower level tiles are available in the panned region, they should be shown.

Provided that the MapTileLayer is assigned to the MapLayer property of the map control (which seems to be what you are doing), lower level tiles are always shown behind higher level ones, up to a maximum level offset that is given by the MaxBackgroundLevels property of the MapTileLayer. Its default value is 8, but you can of course increase it.
