### ISSUE TITLE
Is there a way to know when the map tiles are done rendering?

### ISSUE THREAD

**Issue by ericjut1972** [ClemensFischer/XAML-Map-Control#64]
Hello,

Sorry if it's a basic question, but I couldn't find any Event that would let me know when the map is done rendering the tiles. 

"Loaded" seems to return before any tiles are rendered.

Thank you in advance.

**Comment by ClemensFischer** [comment]
There is nothing like that out of the box. You may try to extend the TileImageLoader class.
