### ISSUE TITLE
Ellipses do not scale with zoom in WPF sample

### ISSUE THREAD

**Issue by zoombinis** [ClemensFischer/XAML-Map-Control#66]
Hi and thank you for this repo,

When zooming, ellipses defined in a `MapItemsControl` do not appear to scale with the zoom level. As you zoom out they get _bigger_ instead of smaller. This is the opposite behavior of a statically defined ellipse, which correctly scales (gets smaller) as you zoom out:

For instance, this works as described above (from your WPF sample app):
```xaml
<map:MapPath Location="53.5,8.2" Stroke="Blue" StrokeThickness="3" Fill="#1F007F00">
                <map:MapPath.Data>
                    <EllipseGeometry RadiusX="1852" RadiusY="1852"/>
                </map:MapPath.Data>
            </map:MapPath>
```

But this doesn't work; Extending your WPF Sample, I display an ellipse for each point location you've defined. They display perfectly fine, but as you zoom out they get bigger (whereas static ellipse stays a fixed size)

```xaml
<Style x:Key="EllipseItemStyle" TargetType="map:MapItem">
            <Setter Property="map:MapPanel.Location" Value="{Binding Location}"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="map:MapItem">
                        <Canvas>
                            <map:MapPath Fill="Red" Opacity="0.7">
                                <map:MapPath.Data>
                                    <EllipseGeometry RadiusX="100" RadiusY="100"/>
                                </map:MapPath.Data>
                            </map:MapPath>
                        </Canvas>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
```

And then beside the other mapcontrols:

```xaml
 <map:MapItemsControl ItemsSource="{Binding Points}"
                                 ItemContainerStyle="{StaticResource EllipseItemStyle}"
                                 SelectionMode="Extended"/>
```

**Comment by ClemensFischer** [comment]
That is perhaps a misconception. Such an Ellipse either scales with the Map's ViewScale, or it has a fixed size in view coordinates, i.e. pixels.

**Comment by zoombinis** [comment]
thanks for the quick response. If you run the example WPF app with my changes, you should notice an inconsistency when zoomed out the ellipses created in the `map:MapItemsControl` do not scale correctly (notice Red ellipses are much bigger than blue even though they were defined with much smaller `Radius` properties):
![sizeDiff](https://user-images.githubusercontent.com/72039888/94481611-febd9100-01a5-11eb-9421-9f4ca62be480.png)

**Comment by ClemensFischer** [comment]
The MapPath in your ControlTemplate doesn't have a Location property set. The Location is set on the templated parent element, i.e. the MapItem.

It doesn't work that way - without a Location, a MapPath can't scale the Geometry in its Data property.

**Comment by ClemensFischer** [comment]
You should be able to do something like

    <Canvas>
        <Canvas.Resources>
            <EllipseGeometry RadiusX="100" RadiusY="100" x:Shared="False" x:Key="Data"/>
        </Canvas.Resources>
        <map:MapPath Fill="Red" Opacity="0.7"
                        Data="{StaticResource Data}"
                        Location="{Binding Location}"/>
    </Canvas>

**Comment by zoombinis** [comment]
That works, and drawing a theoretical ellipse is much more efficient than my work around of drawing a `MapPolygon` of hundreds of NTS points, so thank you for clarifying this.

For anyone else stuck on how to implement drawing enumerable ellipses that scale with zoom level, here's  my fully working `Style` to use in the WPF Sample app:

```xaml
<Style x:Key="EllipseItemStyle" TargetType="map:MapItem">
            <Setter Property="map:MapPanel.Location" Value="{Binding Location}"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="map:MapItem">
                        <Canvas>
                            <Canvas.Resources>
                                <EllipseGeometry
                                    RadiusX="100"
                                    RadiusY="100"
                                    x:Shared="False"
                                    x:Key="Data" />
                            </Canvas.Resources>
                            <map:MapPath 
                                Fill="Red" 
                                Opacity="0.7" 
                                Data="{StaticResource Data}"
                                Location="{Binding Location}" />
                        </Canvas>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
``` 
(Notice location must be bound twice, as without the `Setter Property="map:MapPanel.Location"` nothing would display)

**Comment by YiehraiS** [comment]
Hello, @ClemensFischer! Thank you for your great work!
I have the similar issue but difference is items disappear from map after zoom changed. I need to draw point on some location and add filled circle around it (I call it heat map). There are ~2000 points and I need to draw heat map circles to see cluster fast. The problems are:
- disappearing heat map after zoom changed when I use style from previous comment
- catching _System.InvalidOperationException: 'Cannot set a property on object 'System.Windows.Media.EllipseGeometry' because it is in a read-only state.'_ on line 80 MapPath.cs when I use
`<map:MapItemsControl ItemsSource="{Binding HeatMap}"  ItemContainerStyle="{StaticResource HeatMapStyle}" />
<Style x:Key="HeatMapStyle" TargetType="map:MapItem">
   <Setter Property="map:MapPanel.Location" Value="{Binding Location}"/>
   <Setter Property="ToolTip" Value="{Binding Location}"/>
   <Setter Property="Template">
      <Setter.Value>
         <ControlTemplate TargetType="map:MapItem">
            <Canvas>
               <map:MapPath Location="{Binding Location}" Fill="Green" Opacity="0.2">
                 <map:MapPath.Data>
                    <EllipseGeometry RadiusX="100" RadiusY="100"/>
                 </map:MapPath.Data>
              </map:MapPath>
           </Canvas>
        </ControlTemplate>
     </Setter.Value>
 </Setter>
</Style>`
What I need:
- draw point by locations (~2000)
- add heat map circle to each point
- have possibility to enable/disable heat map (no problem)
- have possibility to change size and opacity of each heat map circle in runtime (can't check yet)

Thanks in advance!

**Comment by ClemensFischer** [comment]
That is not my code, sorry.

**Comment by ClemensFischer** [comment]
You have not used an EllipseGeometry as a shared resource. Take another look.

**Comment by YiehraiS** [comment]
If I use `x:Shared="False"` my circles disappear after zoom changed. And I catch the error if I don't.

**Comment by ClemensFischer** [comment]
You may perhaps do something like shown below. It uses the read-only ViewScale property of the MapBase class, which I have just added - check out the latest sources.

Be aware that this is a scaling factor from projected map coordinates - typically meters in a projected cartesian coordinate system - to view coordinates, i.e. device-independent pixels.

    <map:MapItemsControl ItemsSource="{Binding HeatMap}">
        <map:MapItemsControl.ItemContainerStyle>
            <Style TargetType="map:MapItem">
                <Setter Property="map:MapPanel.Location" Value="{Binding}"/>
            </Style>
        </map:MapItemsControl.ItemContainerStyle>
        <map:MapItemsControl.ItemTemplate>
            <DataTemplate>
                <Path Fill="Green" Opacity="0.2">
                    <Path.Data>
                        <EllipseGeometry RadiusX="100" RadiusY="100"/>
                    </Path.Data>
                    <Path.RenderTransform>
                        <ScaleTransform
                            ScaleX="{Binding ViewScale, ElementName=map}"
                            ScaleY="{Binding ViewScale, ElementName=map}"/>
                    </Path.RenderTransform>
                </Path>
            </DataTemplate>
        </map:MapItemsControl.ItemTemplate>
    </map:MapItemsControl>

**Comment by ClemensFischer** [comment]
@YiehraiS With another recent source update, you can now also directly set the MapPath.Data property

    <Style TargetType="map:MapItem">
        <Setter Property="Location" Value="{Binding Location}"/>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="map:MapItem">
                    <map:MapPath
                        Fill="Green" Opacity="0.2"
                        Location="{TemplateBinding Location}">
                        <map:MapPath.Data>
                            <EllipseGeometry RadiusX="100" RadiusY="100"/>
                        </map:MapPath.Data>
                    </map:MapPath>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

**Comment by YiehraiS** [comment]
> @YiehraiS You may perhaps do something like shown below. It uses the read-only ViewScale property of the MapBase class, which I have just added - check out the latest sources.
> 
> Be aware that this is a scaling factor from projected map coordinates - typically meters in a projected cartesian coordinate system - to view coordinates, i.e. device-independent pixels.
> 
> ```
> <map:MapItemsControl ItemsSource="{Binding HeatMap}">
>     <map:MapItemsControl.ItemContainerStyle>
>         <Style TargetType="map:MapItem">
>             <Setter Property="Location" Value="{Binding Location}"/>
>         </Style>
>     </map:MapItemsControl.ItemContainerStyle>
>     <map:MapItemsControl.ItemTemplate>
>         <DataTemplate>
>             <Path Fill="Green" Opacity="0.2">
>                 <Path.Data>
>                     <EllipseGeometry RadiusX="100" RadiusY="100"/>
>                 </Path.Data>
>                 <Path.RenderTransform>
>                     <ScaleTransform
>                         ScaleX="{Binding ViewScale, ElementName=map}"
>                         ScaleY="{Binding ViewScale, ElementName=map}"/>
>                 </Path.RenderTransform>
>             </Path>
>         </DataTemplate>
>     </map:MapItemsControl.ItemTemplate>
> </map:MapItemsControl>
> ```

In this case circles are not disappeared after zoom changed, but size of each is const despite zoom changing. And by the way it takes a lot of time to load when I use `ScaleTransform` but it doesn't when I don't (just removed it).
![image](https://user-images.githubusercontent.com/37980374/199645921-48c8fd7c-a8b6-42ab-a004-1ac75709164e.png)
![image](https://user-images.githubusercontent.com/37980374/199645974-262d2b96-c94e-4b0b-8dfe-6a707b9aa566.png)

**Comment by YiehraiS** [comment]
> 

This is not working. Circles get disappeared with zoom changes.

**Comment by YiehraiS** [comment]
This option throws the exception
![image](https://user-images.githubusercontent.com/37980374/199647419-b8dafaf8-68ad-4e29-b8e9-2486f2caa867.png)

I will be based on this option when searching for the solution of scaling:
https://github.com/ClemensFischer/XAML-Map-Control/issues/66#issuecomment-1301085272

Thanks for your help, @ClemensFischer!
One more thing I need is to show scale bar (how much meters per 1 visible centimeter) for user. How could it be implemented?

**Comment by ClemensFischer** [comment]
@YiehraiS Please check out the latest sources. For the scale bar, take a look at the MapScale class.

**Comment by ClemensFischer** [comment]
@YiehraiS Forgot a commit last night. Will do later. For the scale bar, see the MapScale class.

**Comment by YiehraiS** [comment]
@ClemensFischer I have tried to use `MapScale` but I doubt that I use it correct or it works correct.
If I just add to map:
```xaml
<map:Map>
   <map:MapScale Width="200" VerticalAlignment="Bottom" HorizontalAlignment="Left"/>
</map:Map>
```
I get the error on line 99
```csharp
line.Measure(size);
```
because calculated before scale is 0 and size depends on it
```csharp
var scale = ParentMap.GetScale(ParentMap.Center).X;
var length = MinWidth / scale;
```
I tried to replace scale with 1 when it is 0 in order to get program launched. In this case scale is shown but when I move map vertically I get weird result: from bottom to top scale is decreasing without changing zoom.
![image](https://user-images.githubusercontent.com/37980374/199811748-22398bd6-a975-44c5-9178-ba13514702b0.png)
![image](https://user-images.githubusercontent.com/37980374/199811801-4b64831a-11ad-4170-b6cd-5f66de35cb09.png)
![image](https://user-images.githubusercontent.com/37980374/199811849-f981d30f-f0a6-4548-9b5a-fce2e5edcc27.png)
![image](https://user-images.githubusercontent.com/37980374/199811906-ce05b336-8a82-437d-ab4f-f1ec58301dc2.png)
![image](https://user-images.githubusercontent.com/37980374/199811976-bf247691-01b7-4128-b2f9-ed79226aaf8b.png)
![image](https://user-images.githubusercontent.com/37980374/199812017-8b91d9d3-65dd-4da7-983b-f8a457286162.png)

**Comment by ClemensFischer** [comment]
@YiehraiS  I've just pushed the recent code changes.

**Comment by ClemensFischer** [comment]
There is now a read-only MapTransform property in the MapItem class, which scales and rotates from map to view coordinates.

It may be used like this:

    <ControlTemplate TargetType="map:MapItem">
        <Path Fill="Green" Opacity="0.2"
                RenderTransform="{Binding MapTransform, RelativeSource={RelativeSource TemplatedParent}}">
            <Path.Data>
                <EllipseGeometry RadiusX="100" RadiusY="100"/>
            </Path.Data>
        </Path>
    </ControlTemplate>
