### ISSUE TITLE
help - map doesnt load

### ISSUE THREAD

**Issue by SioGabx** [ClemensFischer/XAML-Map-Control#67]
Hello,
 I have been trying for few hours to load tiles of OpenStreetMap without success ...
This is what i get : 
![image](https://user-images.githubusercontent.com/41244237/97783818-664a7000-1b9a-11eb-838f-31f7c1262c9a.png)
And this is my MainWindow.xaml : 
`<Window x:Class="GeoportailMap_2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
          xmlns:map="clr-namespace:MapControl;assembly=MapControl.WPF"
        xmlns:local="clr-namespace:GeoportailMap_2"
      
        Title="MainWindow" Height="450" Width="800" Loaded="Window_Loaded">
    <Window.Resources>
        <map:WebMercatorProjection x:Key="WebMercatorProjection"/>
        <map:MapTileLayer x:Key="OpenStreetMap" SourceName="OpenStreetMap"
                              Description="Maps © [OpenStreetMap Contributors](http://www.openstreetmap.org/copyright)"
                              TileSource="https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png"
                              MaxZoomLevel="19" />
        

    </Window.Resources>

    <Grid>
       
        
        <map:Map MapLayer="{StaticResource OpenStreetMap}" ZoomLevel="18" MapProjection="{StaticResource WebMercatorProjection}" >
          
            <map:Map.Center>
                <map:Location Longitude="6.429381" Latitude="48.198846"/>
            </map:Map.Center>

            <map:Pushpin map:MapPanel.Location="65,-18" Content="Iceland"/>
            <map:Pushpin map:MapPanel.Location="71,25" Content="Norway"/>
            <map:Pushpin map:MapPanel.Location="35,33" Content="Cyprus"/>
            <map:Pushpin map:MapPanel.Location="28.25,-16.5" Content="Tenerife"/>
            <map:Pushpin map:MapPanel.Location="48,3" Content="France"/>
        </map:Map>
       
    </Grid>
</Window>`

Do you know what I must have missed when trying to interpret the examples?
If you want i have uploaded my project here : https://github.com/SioGabx/geoportail_2_.git
Thank you in advance for your help !

**Comment by ClemensFischer** [comment]
Your code works fine for me with the latest XAML-Map-Control version 5.4.0 - which is not yet available via NuGet.

In case you have used an older version, change the `{s}` subdomain format specifier in the tile URL to `{c}`.
