### ISSUE TITLE
WmtsTileLayer doesnt load a specific map 

### ISSUE THREAD

**Issue by SioGabx** [ClemensFischer/XAML-Map-Control#68]
Hello,
I tried to load a french map inside the map control but in the GetCapabilities there's no ressource template (i think its this..) because when i put in the CapabilitiesUri this uri, its work perfect : https://sgx.geodatenzentrum.de/wmts_topplus_open/1.0.0/WMTSCapabilities.xml

The GetCapabilities of the map i tried to add : 
http://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities

A working template of the service
https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?layer=ORTHOIMAGERY.ORTHOPHOTOS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=20&TileCol=531433&TileRow=361001

How can i make it work ? 

The C# code to load this map...
```
mapviewer.MapLayer = new WmtsTileLayer
            {
                SourceName = "geoportail",
                Description = "testing...",
                CapabilitiesUri = new Uri("http://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities"),
               //TileSource = new TileSource { UriFormat = "https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?layer=ORTHOIMAGERY.ORTHOPHOTOS&style=normal&tilematrixset={TileMatrixSet}&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix={TileMatrix}&TileCol={TileCol}&TileRow={TileRow}" },
                LayerIdentifier = "ORTHOIMAGERY.ORTHOPHOTOS"
            };
```

Thank a lot for your precious help and sorry for my bad english ^^'

**Comment by ClemensFischer** [comment]
Please take a look at potential error messages. Your sample code generates this:

    WmtsTileLayer: http://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities: No valid ResourceURL element found in Layer "ORTHOIMAGERY.ORTHOPHOTOS".

It indicates that the Layer description in the GetCapabilities response misses an URL format for the associated map request URL. It seems the service only supports the KVP encoding, which is not supported by XAML MapControl.

I may take a closer look at a possible implementation of KVP encoding when I find the time. However, this encoding does not seem to be very common.

**Comment by SioGabx** [comment]
Then there is maybe a function to juste give a template URL and XAML MapControl replace just {TileMatrix}, {TileCol} and {TileRow} ?

**Comment by ClemensFischer** [comment]
As said, the service does not seem to implement the REST protocol, only KVP.

**Comment by ClemensFischer** [comment]
Not yet. I will have a look. Maybe there is a way to specify something like a default URL format.

Be aware that currently there is nothing in the GetCapabilities response that would give an indication of the `Style={Style}`, `Version=1.0.0` and `Format=imge/jpeg` URL parameters. IMO, if that service is supposed to serve the RESTful protocol, it is not configured correctly.

**Comment by ClemensFischer** [comment]
After reading the WMTS specs one more time, I realized there is no need to retrieve a `ResourceURL` in a WMTS Layer when the service uses the so-called "procedure oriented architectural style" - in contrast to the "resource oriented architectural style". You can simply construct an URL template from a set of default URL query parameters.

I have modified the WmtsCapabilities class accordingly, which you may download from this site. I will also publish the next release on NuGet soon.

Note that in your sample program you will also need to set a value for the HTTP User-Agent header that is used by the library's ImageLoader class, e.g. like

    ImageLoader.HttpClient.DefaultRequestHeaders.Add("User-Agent", "WMTS Test Application");

**Comment by SioGabx** [comment]
Thanks you for your time ! :D
