### ISSUE TITLE
Load tiles from the inside to the edges

### ISSUE THREAD

**Issue by andyesys** [ClemensFischer/XAML-Map-Control#69]
Would it be possible to adjust the algorithm for loading the tiles so that the tiles in the center of the map window are always loaded first and then the others up to the edge? This would help users see what they are interested in more quickly.

PS: Thank you for your great work!

**Comment by ClemensFischer** [comment]
You may change the order in which tiles are passed to the TileImageLoader (in MapTilerLayer and WmtsTileLayer). There is however no guarantee that a loading order is always retained, since tile loading runs asynchronously.

**Comment by andyesys** [comment]
It would be great to have an extension point for custom tile sorting before the tiles are loaded here: https://github.com/ClemensFischer/XAML-Map-Control/blob/f38ac5bec3d335e5ed2a8df8f4166b4165033a79/MapControl/Shared/MapTileLayer.cs#L149

Currently I have to reimplement the entire MapTileLayer to be able to sort the list from inside outwards before that line.

**Comment by ClemensFischer** [comment]
I could think of a virtual method in MapTileLayerBase like

    protected virtual void LoadTiles(IEnumerable<Tile> tiles, string sourceName = null)
    {
        TileImageLoader.LoadTiles(tiles, TileSource, sourceName ?? SourceName);
    }

**Comment by andyesys** [comment]
> I could think of a virtual method in MapTileLayerBase like
> 
> ```
> protected virtual void LoadTiles(IEnumerable<Tile> tiles, string sourceName = null)
> {
>     TileImageLoader.LoadTiles(tiles, TileSource, sourceName ?? SourceName);
> }
> ```

Yes it would be great if you could add this. We could sort tiles before calling `base.LoadTiles()`. Thank you very much!

**Comment by ClemensFischer** [comment]
Please see the latest commit. There is also a new NuGet package.

**Comment by andyesys** [comment]
Today I got to test the new virtual method and it works as expected. 

The following example class allows easy sorting of the tiles from inside to outside before loading:

```csharp
public class SortedMapTileLayer : MapTileLayer
{
    protected override void LoadTiles(IEnumerable<Tile> tiles, string cacheName)
    {
        if (tiles.Any())
        {
            var centers = tiles
                .GroupBy(x => x.ZoomLevel, (key, tiles) => new
                {
                    key,
                    midX = tiles.Average(x => x.X),
                    midY = tiles.Average(x => x.Y)
                })
                .ToDictionary(x => x.key);
            static double sq(double x) => x * x;
            var sortedTiles = tiles
                .OrderBy(x => x.ZoomLevel)
                .ThenBy(x => sq(centers[x.ZoomLevel].midX - x.X) + sq(centers[x.ZoomLevel].midY - x.Y));
            base.LoadTiles(sortedTiles, cacheName);
        }
        else
        {
            base.LoadTiles(tiles, cacheName);
        }
    }
}
```
