### ISSUE TITLE
Version History

### ISSUE THREAD

**Issue by lightwalker01** [ClemensFischer/XAML-Map-Control#7]
Hi @ClemensFischer,
Is there a version history somewhere?
I have to compare code to know what are changes between 3.0.0 and 4.2.0?
Thank you for your work!

**Comment by ClemensFischer** [comment]
You mean besides what is provided by the GitHub repository? I guess not.

**Comment by lightwalker01** [comment]
Yes, I mean that there are no releases and it's hard to know what new features have been implemented or bugs fixed...
![image](https://user-images.githubusercontent.com/7263833/31623206-064f6762-b29f-11e7-87b4-30772384d807.png)

Thank you anyway.
Regards
