### ISSUE TITLE
Get current map boundaries

### ISSUE THREAD

**Issue by husk3rdu** [ClemensFischer/XAML-Map-Control#70]
Hi,

Would it be possible to get the current map boundaries? I mean w/e/n/s coordinates... 
The idea is to filter an ICollectionView dinamically based on the current map view.
 
Thanks!

**Comment by ClemensFischer** [comment]
Use the Map's `ViewRectToBoundingBox` method, like

    var bbox = map.ViewRectToBoundingBox(new Rect(0, 0, map.ActualWidth, map.ActualHeight));

**Comment by husk3rdu** [comment]
Great! Thanks!
