### ISSUE TITLE
map:HyperlinkText.InlinesSource does not work

### ISSUE THREAD

**Issue by WalhallaZ** [ClemensFischer/XAML-Map-Control#75]
When control is used from a NuGet package in a .NET 5 project, map:HyperlinkText.InlinesSource does not open external browser as UseShellExecute property of ProcessStartInfo is not set to true.

NuGet package reports last update as "2 months ago", however source code of the file was fixed in 
a commit 7fb875347a311b7cab73ed23df55cc18ff3103db, so I'm asking you kindly to update the package, if possible, as for now it is only possible to compile the library from the source code.

**Comment by ClemensFischer** [comment]
Or you simply use your own version of HyperlinkText. It's just a convenience class.
