### ISSUE TITLE
Пожалуйста пример.

### ISSUE THREAD

**Issue by AlexLan73** [ClemensFischer/XAML-Map-Control#76]
Good day.
Please give a working example of a map on wpf
Sincerely, Alexander.
p.s. can't start ((((

**Comment by andyesys** [comment]
The WPF sample app works for me: https://github.com/ClemensFischer/XAML-Map-Control/tree/master/SampleApps/WpfApplication

**Comment by AlexLan73** [comment]
Thank you very much))))
