### ISSUE TITLE
Question: Map boundaries 

### ISSUE THREAD

**Issue by rolikoff** [ClemensFischer/XAML-Map-Control#79]
What would be the best way to get rid of empty tiles (see pic) 
![image](https://user-images.githubusercontent.com/2165312/136539049-b43749f6-60cc-44d3-82ed-d0512a0166ec.png)

At the moment, I have a class derived from MabBase where I can get access to all OnMouseMove events, I can get the bounding box and make sure that South and North is between 85 and -85. But that doesn't look a nice way to handle this issue.  Also why those empty tiles are there?

**Comment by ClemensFischer** [comment]
The OpenStreetMap tiling scheme is limited to the latitude range -85.051 .. 85.051. There are no tiles beyond these bounds.

You may set an appropriate Background Brush, or just set the MinZoomLevel to 1 or 2.

**Comment by rolikoff** [comment]
Well that doesn't quite what I want to do. Setting zoom to even 3 wont fix the issue, example:
![image](https://user-images.githubusercontent.com/2165312/136567529-56520d55-df9b-4696-9a16-879c28a91564.png)

If I set the background color for the map control to the same color as the earth color, North pole wont look well. 
So what I do now is this: 
```
        private void OnMouseMove(object sender, MouseEventArgs e)
        {
            if (mousePosition.HasValue)
            {
                var position = e.GetPosition(this);
                var translation = position - mousePosition.Value;
                mousePosition = position;

                var viewTopLeft = ViewTransform.ViewToMap(new Point(0, 0));
                var viewBottomLeft = ViewTransform.ViewToMap(new Point(0, RenderSize.Height));

                var mapTopLeft = this.MapProjection.MapToLocation(viewTopLeft);
                var mapBottomLeft = this.MapProjection.MapToLocation(viewBottomLeft);


                var locatioEdgeNorth = MapProjection.LocationToMap(new Location(84.99, 0));
                var locatioEdgeSouth = MapProjection.LocationToMap(new Location(-84.99, 0));

                if (mapTopLeft.Latitude > 85)
                {
                    translation.Y = -ViewTransform.MapToView(locatioEdgeNorth).Y;
                }
                if (mapBottomLeft.Latitude < -85)
                {
                    translation.Y = ViewTransform.MapToView(locatioEdgeSouth).Y;
                }

                TranslateMap(translation);
            }
        }
        ```
Kinda trying to limit the transition for mouse move.
