### ISSUE TITLE
Assembly 'MapControl.WPF' not found

### ISSUE THREAD

**Issue by raabesebastian** [ClemensFischer/XAML-Map-Control#81]
With Visual Studio 2022 and switching to .NET 6.0, a WPF application can't reference to MapControl.WPF:

`xmlns:map="clr-namespace:MapControl;assembly=MapControl.WPF"`

Maybe because .NET 6.0 comes with the new namespace `xmlns:map="MapControl.WinUI"`

Edit: My fault. If you set the target SDK to 10.0.X, the error appears. If you leave the target at 7.0, it works.

**Comment by ClemensFischer** [comment]
I have just released version 7.0 on NuGet, with a .NET 6.0 platform target for MapControl.WPF
