### ISSUE TITLE
Zoom Center (with offset) to position pushpin at exact location on screen

### ISSUE THREAD

**Issue by c-emin** [ClemensFischer/XAML-Map-Control#82]
I am iterating through a collection of lat/lon coordinates of pushpins. To create a SlideShow of locations.
I am using      map.TargetCenter = new Location(lat,lon);
All works great up to this point.  

Now I would like to offset where the pushpin location is showing on the screen. Down and to the left.

If I use map.TargetCenter = new Location(lat+1.5,lon+7);
It puts it close to where I want it.. but it is not consistently positioning in the latitude for the range(-80,80)

Is there an easy way to offset the viewport by number of pixels?
Or is there a special method that applies a formula to a correct adjusted offset based on the lat coordinate.

I've tried to use YToLatitude method to get the offset needed at that latitude, and also tied to use Pixels per degree .71111  
But could not get anything to work consistently.

Any help would be appreciated.

**Comment by ClemensFischer** [comment]
If you want to move the map center by a certain offset in view coordinates, you should perhaps use the LocationToView and ViewToLocation methods.
