### ISSUE TITLE
High memory usage when run in Windows 11

### ISSUE THREAD

**Issue by EjiHuang** [ClemensFischer/XAML-Map-Control#83]
Hi, @ClemensFischer 
When I keep loading the map tiles, the memory usage keeps increasing.
And cannot be executed gc.
This issue only occurs on Windows 11.
In Windows 10, everything is working fine.

**Comment by ClemensFischer** [comment]
I'll have a look into it as soon as I am on Windows 11.

**Comment by ClemensFischer** [comment]
Can't confirm anything like this, neither for WPF, nor UWP or WinUI.

**Comment by EjiHuang** [comment]
![image](https://user-images.githubusercontent.com/10510947/144775300-4f429aa0-0844-4d4a-b16a-fed6dd9ce74b.png)
I don‘t know why. My Windows 11 is version 21H2 22000.348.
Maybe it might be my system issue. I will continue to investigate the issue, thank you.
