### ISSUE TITLE
[WPF] About the performance of MapPolyline.

### ISSUE THREAD

**Issue by EjiHuang** [ClemensFischer/XAML-Map-Control#84]
Hi @ClemensFischer 

I have a flight path with more than 120,000 points. And I want to use MapPolyline to show this flight path on map. But, it will make the map control stuck. So, when I move and zoom the map control, UpdateData() function will invoke in class MapPolyline. This function will make these points generate polyline again.

If I need to load this flight path, can you give me some suggestions?
Thank you.

**Comment by ClemensFischer** [comment]
You would somehow have to adjust the number of points according to the visible parts of a polyline. If zoomed out, the number should be reduced, e.g. by the [Ramer–Douglas–Peucker algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm). When zoomed in, parts outside the visible viewport should be cut off. There is however nothing like this built into the MapPolyline class.

**Comment by EjiHuang** [comment]
Thank you. I will try this.
