### ISSUE TITLE
Pushpin alignment is Top-Left

### ISSUE THREAD

**Issue by rurounijones** [ClemensFischer/XAML-Map-Control#85]
First up, I love this project, it has been incredibly useful.

XAML.MapControl Version: 7.2.0

I am adding pushpins to the maps and they do not appear to be aligning so bottom left point of the pushpin is at the location but the top left is.

You can see the Lat/Lon values in the pushpin content and see that the origin is not where the bottom point is coming from. It is clearest on the white markers for the map area edge and points where the polygon lines meet where the point should be on the junction of two lines.

I have included a minimal set of XAML at the bottom of this issue. I am probably missing something obvious but cannot figure it out.

I have tried adding 

```xml
  <Setter Property="HorizontalAlignment" Value="Center"/>
  <Setter Property="VerticalAlignment" Value="Bottom"/>
```

To the pushpin with various combinations of alignment values but that doesn't do anything (I am not entirely sure if that is the pushpin itself or the text within).

Any help would be much appreciated and apologies if I am missing something obvious.

![image](https://user-images.githubusercontent.com/21911/155156701-db52d546-0629-4f36-8ecc-75d93e4df682.png)

```xml
</Window>
    <Window.Resources>
        <local:UnitSiteLocationConverter x:Key="UnitSiteLocationConverter"/>
        <local:UnitSiteColorConverter x:Key="UnitSiteColorConverter"/>
        <local:CoordinateLocationConverter x:Key="CoordinateLocationConverter"/>
        <mapControl:WebMercatorProjection x:Key="WebMercatorProjection"/>
        <Style x:Key="RedForPolygonStyle" TargetType="mapControl:MapItem">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="mapControl:MapItem">
                        <mapControl:MapMultiPolygon Polygons="{Binding Converter={StaticResource CoalitionPolygonConverter}}" Stroke="Red" StrokeThickness="1" Fill="#55aa0000"/>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
        <Style x:Key="CoordinateStyle" TargetType="mapControl:MapItem">
            <Setter Property="Location" Value="{Binding Converter={StaticResource CoordinateLocationConverter}}"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="mapControl:MapItem">
                        <mapControl:Pushpin Content="{Binding}" />
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </Window.Resources>
        <mapControl:Map x:Name="MainMap" ZoomLevel="{Binding ZoomLevel}" MaxZoomLevel="21" MouseWheelZoomDelta="1"
                        Center="{Binding MapLocation}">
            <mapControl:Map.MapProjection>
                <StaticResource ResourceKey="WebMercatorProjection"/>
            </mapControl:Map.MapProjection>
            <mapControl:MapItemsControl ItemsSource="{Binding RedForPolygons}"
                                        ItemContainerStyle="{StaticResource RedForPolygonStyle}"
                                        Visibility="Visible"/>
            <mapControl:MapItemsControl ItemsSource="{Binding Coordinates}"
                                        ItemContainerStyle="{StaticResource CoordinateStyle}"
                                        Visibility="Visible"/>
        </mapControl:Map>
    </Grid>
</Window>
```

**Comment by ClemensFischer** [comment]
There should be

    <Setter Property="VerticalAlignment" Value="Bottom"/>

in the CoordinateStyle, just like in the PushpinItemStyle in the sample application.

**Comment by rurounijones** [comment]
Well, that is embarrasing. I did try it with the two alignment property setters (as mentioned above) and even used https://github.com/ClemensFischer/XAML-Map-Control/blob/ebd0bdf216a63076dda83cacbfdf3ed1765c3590/SampleApps/WpfApplication/MainWindow.xaml#L85-L86 as a reference and it didn't appear to have an effect at the time but I just tried it again and it works.

No idea what I did wrong previously. Sorry for the noise.

**Comment by raabesebastian** [comment]
> There should be
> 
> ```
> <Setter Property="VerticalAlignment" Value="Bottom"/>
> ```
> 
> in the CoordinateStyle, just like in the PushpinItemStyle in the sample application.
> 
> Note that since this version you can also set HorizontalAlignment to Center or Right and the Pushpin pointer will appear in the center or on the right side.

Is there a reason why the pointer is now centered? Is it possible to set the pointer to left again, like on the screenshot?

**Comment by ClemensFischer** [comment]
> Is there a reason why the pointer is now centered?

Yes, because Center is the HorizontalAlignment value in the default Style now.

> Is it possible to set the pointer to left again, like on the screenshot?

Sure, set a different value if you want a different appearence.

**Comment by raabesebastian** [comment]
> > Is there a reason why the pointer is now centered?
> 
> Yes, because Center is the HorizontalAlignment value in the default Style now.
> 
> > Is it possible to set the pointer to left again, like on the screenshot?
> 
> Sure, set a different value if you want a different appearence.

Sorry, I set the HorizontalAlignment to left and wondered why it doesn't work. Now I found out, that the changes took on the application restart effect, not on hot reload. Thank you.
