### ISSUE TITLE
Support for XAMARIN

### ISSUE THREAD

**Issue by ImCarrot** [ClemensFischer/XAML-Map-Control#9]
Hi, i am working on a xamarin project, was wondering if there is a compatiple version of this control for  xamarin. Could you please help?

**Comment by ClemensFischer** [comment]
Sorry, there's no version for Xamarin. I've never used it, so can't help you there. However, this project is open source, so you may just takes the sources and try to compile and run it with Xamarin. Note however that this project will not accept any pull requests.
