### ISSUE TITLE
Offline Bing maps not showing

### ISSUE THREAD

**Issue by Bondarenko1990** [ClemensFischer/XAML-Map-Control#90]
I launch these samples - UWP, WinUI. 
Why are bing maps not showing without internet? And the OpenStreetMap maps are displayed normally.
Could you help me?
![image](https://user-images.githubusercontent.com/32612104/194704154-e4e641a7-6260-4dd9-8bd9-26d45f8257b3.png)
OpenStreetMap
![image](https://user-images.githubusercontent.com/32612104/194704175-61badde2-a098-4442-862e-b758b6934a11.png)
Bing map

**Comment by ClemensFischer** [comment]
Bing Maps access does not work without an initial [Imagery Metadata](https://learn.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata) request.

**Comment by Bondarenko1990** [comment]
@ClemensFischer And than Why does that MapControl work in offline with bing maps? https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.maps?view=winrt-22621
