### ISSUE TITLE
Thank you! and a question

### ISSUE THREAD

**Issue by jianyunli** [ClemensFischer/XAML-Map-Control#91]
Hi Clemens

Thank you for this excellent work, I am using WPF version of it,  MapItem are based on Shape, I need to improve performance for tens of thousands of lines/polygons to overlay on the map, I created Framework Element host with DrawingVisuals children, how do I put this element on the Map? by setting the BoundingBox like the Image in the sample? 

`map:MapPanel.BoundingBox="53.54031,8.08594,53.74871,8.43750"="53.54031,8.08594,53.74871,8.43750"`

**Comment by ClemensFischer** [comment]
Impossible to tell without any information about that element. What happens if you try to set the BoundingBox?

**Comment by jianyunli** [comment]
wish we have a place to ask questions :) I tried following, it does not work

I created a Framework element host and added DrawingVisual children to it, then added this host to the Map and set its BoundingBox.

When I pan, it's stay in the same place, but when I zoom, this Box stays the same size in pixels, means when I zoom out of the map, this box covers larger area

I think your MapPath should do what I intended, but I don't want to use Shape, I have more than thousands of Polygons and lines etc., I need them to be lightweight so using DrawingVisual

`
        private void AddUIButton_Click(object sender, RoutedEventArgs e)
        {
            var host = new MyVisualHost();
            DrawingVisual drawingVisual = new DrawingVisual();
            DrawingContext drawingContext = drawingVisual.RenderOpen();

            Rect rect = new Rect(new Point(0, 0), new System.Windows.Size(320, 160));
            Pen myPen = new Pen();
            myPen.Brush = Brushes.Red;
            myPen.Thickness = 2;
            drawingContext.DrawRectangle(null, myPen, rect);
            drawingContext.Close();
            host.Child = drawingVisual;

            map.Children.Add(host);
            MapPanel.SetBoundingBox(host, new BoundingBox(53.54031, 8.08594, 53.74871, 8.43750));
        }
`

**Comment by ClemensFischer** [comment]
The problem is that your VisualHost does not do any layout, i.e. it does not arrange its child visual.
