### ISSUE TITLE
NET452 support

### ISSUE THREAD

**Issue by YiehraiS** [ClemensFischer/XAML-Map-Control#94]
Could you add support of NET452. I understand that it is old version but some developers are still using it because of compatibility. E.g., I've done it for my local version of fork. There will be a little changes like:
```csharp
#if NET452
   return Task.FromResult(0);
#else
   return Task.CompletedTask;
#endif
```
and
```csharp
#if !NET452
   var pixelsPerDip = VisualTreeHelper.GetDpi(this).PixelsPerDip;
#endif
```
Thanks in advance!

**Comment by ClemensFischer** [comment]
.NET Framework version before 4.6.2 will not be supported.
