### ISSUE TITLE
Wms apparently disappear on failed maptile request

### ISSUE THREAD

**Issue by radiothom** [ClemensFischer/XAML-Map-Control#96]
Hi all!
I apologize if I use this space improperly to report a possible problem.
I've been using this wonderful control with great satisfaction, since the first Silverlight version, but I'm facing a problem that I can't get out of. 
Briefly: on the map I have two layers: a custom maptile that I use as background map instead of Bing Maps and, immediately above it, a wms. The problem is that, occasionally, due to the bottlenecks of the server from which I publish the tile, some tile requests fail. The moment this happens, the wms above disappears. I can't figure out where the problem is. The published maptile adheres to the schema used by OSM tiles. 
Any suggestion will be very welcome. Thank you

**Comment by ClemensFischer** [comment]
Without example code that reproduces the problem, it is impossible to analyze it or provide any help.
